# Talent Acquisition Data Analysis

- Synthesizes key findings from the data.  
- Shares any key issues related to the data format or quality that youâ€™d want to try and change.

## Import stuff needed

In [949]:
import pandas as pd
import numpy as np

from matplotlib import pyplot as plt
import seaborn as sns

plt.style.use('fivethirtyeight')

%matplotlib inline

## Read in the data

I did save the .xlsx file as a .csv file to be able to import the data to my Jupyter notebook.

In [950]:
appquest = pd.read_csv('./ApplicationQuestions.csv')

In [951]:
apps = pd.read_csv('./Applications.csv')

/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [952]:
sourcemap = pd.read_csv('./Source_Mapping.csv')

## What does the data look like?

### Application Questions

In [953]:
appquest.head(3)

,CANDIDATE_ID,APPLICATION_ID,JOB_REF_ID,JOB_TITLE,DEPARTMENT,POSITION_CATEGORY,POSITION,REGION,USI_DIVERSITY_QUESTION_RACE,USI_DIVERSITY_QUESTION_GENDER,USI_UNCOMMON_AFFILIATION,USI_GPA,USI_TEACHER_CERT,USI_TEACHING_EXPERIENCE,USI_HEARD_ABOUT_UNCOMMON,USI_OTHER_AFFILIATION
0,e9263572-f945-4e2e-bf66-6ae0c25c56f5,f72b1b7e-f35f-4f2a-aa79-cb29c8ff73e6,REF13L,Dean of Students,Student Services,Student Support,Dean Of Students,Troy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ae78dd81-4525-4825-8981-a0f9bc301c14,ae78dd81-4525-4825-8981-a0f9bc301c14,REF8Q,Apprentice Teacher (Immediate Start SY 18-19),Teaching and Instruction,Apprentice Teacher,Apprentice Teacher,Rochester,Multi-racial,Female,None of the above.,3.0-3.5,No,Less than one year,Current or former Uncommon staff member,None of the above
2,97c1bcb8-eb94-4d19-b324-f9ce5c2ed7c0,2a787e27-f8a2-4eab-9cfd-5884a357fc15,REF93W,Receptionist (Immediate Start),School-Based Operations,School Based Operations,Receptionist,Newark,I prefer not to say,Female,None of the above.,NaN,NaN,NaN,Current or Former Uncommon Staff Member,NaN

In [954]:
appquest.shape

(32558, 16)

In [955]:
appquest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32558 entries, 0 to 32557
Data columns (total 16 columns):
CANDIDATE_ID                     32558 non-null object
APPLICATION_ID                   32558 non-null object
JOB_REF_ID                       32558 non-null object
JOB_TITLE                        32558 non-null object
DEPARTMENT                       32558 non-null object
POSITION_CATEGORY                32558 non-null object
POSITION                         32558 non-null object
REGION                           21690 non-null object
USI_DIVERSITY_QUESTION_RACE      28060 non-null object
USI_DIVERSITY_QUESTION_GENDER    27830 non-null object
USI_UNCOMMON_AFFILIATION         28791 non-null object
USI_GPA                          12930 non-null object
USI_TEACHER_CERT                 8030 non-null object
USI_TEACHING_EXPERIENCE          9787 non-null object
USI_HEARD_ABOUT_UNCOMMON         27086 non-null object
USI_OTHER_AFFILIATION            23211 non-null object
dtypes: object(16)
memory usage: 4.0+ MB

### Applications

In [956]:
apps.head(3)

,CANDIDATE_ID,Application Creation Date,APPLICATION_ID,Job Title,Position,Position Category,Region,Grade Level,HO Team,Application Status,...,Application Withdrawal Date,withdrawal Reason,Application field: Secondary Withdrawal Reason,Unnamed: 18,Time In Application State: Lead,Time In Application State: New,Time In Application State: In-Review,Time In Application State: Interview,Time In Application State: Offered,Source
0,79ce3270-7309-4d5a-af10-cc1e57ad7c3a,2019-02-25T17:45:47,79ce3270-7309-4d5a-af10-cc1e57ad7c3a,Special Assistant to the CEO,Associate Director,Home Office,NaN,NaN,Special Projects,REJECTED,...,NaN,NaN,NaN,False,NaN,1.0,8.0,NaN,NaN,Default Career Page
1,66702e53-38c1-4522-938c-25fdcb6e28c1,2019-03-15T16:50:39,e7f9bfd9-1b44-41ba-86ba-b8a9970dfc4c,Special Assistant to the CEO,Associate Director,Home Office,NaN,NaN,Special Projects,REJECTED,...,NaN,NaN,NaN,False,NaN,1.0,1.0,NaN,NaN,Default Career Page
2,a7f35403-1b53-425b-ae00-eb38c728d369,2019-01-22T21:37:02,a7f35403-1b53-425b-ae00-eb38c728d369,Special Assistant to the CEO,Associate Director,Home Office,NaN,NaN,Special Projects,REJECTED,...,NaN,NaN,NaN,False,NaN,1.0,NaN,NaN,NaN,LinkedIn

In [957]:
apps.shape

(33771, 25)

In [958]:
apps.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33771 entries, 0 to 33770
Data columns (total 25 columns):
CANDIDATE_ID                                      33771 non-null object
Application Creation Date                         33771 non-null object
APPLICATION_ID                                    33771 non-null object
Job Title                                         33771 non-null object
Position                                          32486 non-null object
Position Category                                 32486 non-null object
Region                                            21602 non-null object
Grade Level                                       14618 non-null object
HO Team                                           10884 non-null object
Application Status                                33771 non-null object
Application Transfer Date                         276 non-null object
Application Status Before Rejection               29391 non-null object
Unnamed: 12                                       29391 non-null object
Unnamed: 13                                       26491 non-null object
Application Status Before Withdrawal              2642 non-null object
Application Withdrawal Date                       2642 non-null object
withdrawal Reason                                 2616 non-null object
Application field: Secondary Withdrawal Reason    7 non-null object
Unnamed: 18                                       33771 non-null bool
Time In Application State: Lead                   4883 non-null float64
Time In Application State: New                    28820 non-null float64
Time In Application State: In-Review              22027 non-null float64
Time In Application State: Interview              2153 non-null float64
Time In Application State: Offered                374 non-null float64
Source                                            33766 non-null object
dtypes: bool(1), float64(5), object(19)
memory usage: 6.2+ MB

In [959]:
# Make corretions to the column headings
apps = apps.rename(columns={"Unnamed: 12": "Application Rejection Date  ", "Unnamed: 13": "Rejection Reason",
                     "withdrawal Reason": "Withdrawal Reason", "Unnamed: 18": "[Unknown]"})

In [960]:
apps.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33771 entries, 0 to 33770
Data columns (total 25 columns):
CANDIDATE_ID                                      33771 non-null object
Application Creation Date                         33771 non-null object
APPLICATION_ID                                    33771 non-null object
Job Title                                         33771 non-null object
Position                                          32486 non-null object
Position Category                                 32486 non-null object
Region                                            21602 non-null object
Grade Level                                       14618 non-null object
HO Team                                           10884 non-null object
Application Status                                33771 non-null object
Application Transfer Date                         276 non-null object
Application Status Before Rejection               29391 non-null object
Application Rejection Date                        29391 non-null object
Rejection Reason                                  26491 non-null object
Application Status Before Withdrawal              2642 non-null object
Application Withdrawal Date                       2642 non-null object
Withdrawal Reason                                 2616 non-null object
Application field: Secondary Withdrawal Reason    7 non-null object
[Unknown]                                         33771 non-null bool
Time In Application State: Lead                   4883 non-null float64
Time In Application State: New                    28820 non-null float64
Time In Application State: In-Review              22027 non-null float64
Time In Application State: Interview              2153 non-null float64
Time In Application State: Offered                374 non-null float64
Source                                            33766 non-null object
dtypes: bool(1), float64(5), object(19)
memory usage: 6.2+ MB

### Source Mapping

In [961]:
sourcemap.head(3)

,Source,Adjusted_Source,Adjusted_Source_SubType,Adjusted_Source_Type,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16350,Unnamed: 16351,Unnamed: 16352,Unnamed: 16353,Unnamed: 16354,Unnamed: 16355,Unnamed: 16356,Unnamed: 16357,Unnamed: 16358,Unnamed: 16359
0,Future Leaders Incubator,FLI,Teacher Placement,Agency,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Indeed,Indeed,Indeed,Job Board,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Michael Page,HO Agency,HO Agency,Agency,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [962]:
# I took the columns that was not in use away from the dataframe
sourcemap = sourcemap.iloc[:,0:4]

sourcemap.head(3)

,Source,Adjusted_Source,Adjusted_Source_SubType,Adjusted_Source_Type
0,Future Leaders Incubator,FLI,Teacher Placement,Agency
1,Indeed,Indeed,Indeed,Job Board
2,Michael Page,HO Agency,HO Agency,Agency

In [963]:
sourcemap.shape

(206, 4)

In [964]:
sourcemap.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Data columns (total 4 columns):
Source                     206 non-null object
Adjusted_Source            206 non-null object
Adjusted_Source_SubType    206 non-null object
Adjusted_Source_Type       205 non-null object
dtypes: object(4)
memory usage: 6.5+ KB

### How much missing data do we actually have?

In [965]:
appquest.isnull().sum()

CANDIDATE_ID                         0
APPLICATION_ID                       0
JOB_REF_ID                           0
JOB_TITLE                            0
DEPARTMENT                           0
POSITION_CATEGORY                    0
POSITION                             0
REGION                           10868
USI_DIVERSITY_QUESTION_RACE       4498
USI_DIVERSITY_QUESTION_GENDER     4728
USI_UNCOMMON_AFFILIATION          3767
USI_GPA                          19628
USI_TEACHER_CERT                 24528
USI_TEACHING_EXPERIENCE          22771
USI_HEARD_ABOUT_UNCOMMON          5472
USI_OTHER_AFFILIATION             9347
dtype: int64

In [966]:
apps.isnull().sum()

CANDIDATE_ID                                          0
Application Creation Date                             0
APPLICATION_ID                                        0
Job Title                                             0
Position                                           1285
Position Category                                  1285
Region                                            12169
Grade Level                                       19153
HO Team                                           22887
Application Status                                    0
Application Transfer Date                         33495
Application Status Before Rejection                4380
Application Rejection Date                         4380
Rejection Reason                                   7280
Application Status Before Withdrawal              31129
Application Withdrawal Date                       31129
Withdrawal Reason                                 31155
Application field: Secondary Withdrawal Reason    33764
[Unknown]                                             0
Time In Application State: Lead                   28888
Time In Application State: New                     4951
Time In Application State: In-Review              11744
Time In Application State: Interview              31618
Time In Application State: Offered                33397
Source                                                5
dtype: int64

In [967]:
sourcemap.isnull().sum()

Source                     0
Adjusted_Source            0
Adjusted_Source_SubType    0
Adjusted_Source_Type       1
dtype: int64

### Do we have any duplicated inputs?

In [968]:
appquest.duplicated().sum()

0

In [969]:
appquest['CANDIDATE_ID'].duplicated().sum()

5988

In [ ]:
# A candidate can apply for more than one position

In [970]:
appquest['APPLICATION_ID'].duplicated().sum()

0

In [971]:
apps.duplicated().sum()

0

In [972]:
apps['CANDIDATE_ID'].duplicated().sum()

6197

In [ ]:
# A candidate can apply for more than one position

In [973]:
apps['APPLICATION_ID'].duplicated().sum()

0

In [974]:
sourcemap.duplicated().sum()

0

People have applied more than 1 time to different postings.
Therefore it's better to use APPLICATION_ID instead of CANDIDATE_ID when joining the dataframes.

## Create one dataframe

In [975]:
# Make an right outer join on APPLICATION_ID
data = pd.merge(how='right', left=appquest,right=apps, left_on='APPLICATION_ID', right_on='APPLICATION_ID')

data.head(3)

,CANDIDATE_ID_x,APPLICATION_ID,JOB_REF_ID,JOB_TITLE,DEPARTMENT,POSITION_CATEGORY,POSITION,REGION,USI_DIVERSITY_QUESTION_RACE,USI_DIVERSITY_QUESTION_GENDER,...,Application Withdrawal Date,Withdrawal Reason,Application field: Secondary Withdrawal Reason,[Unknown],Time In Application State: Lead,Time In Application State: New,Time In Application State: In-Review,Time In Application State: Interview,Time In Application State: Offered,Source
0,e9263572-f945-4e2e-bf66-6ae0c25c56f5,f72b1b7e-f35f-4f2a-aa79-cb29c8ff73e6,REF13L,Dean of Students,Student Services,Student Support,Dean Of Students,Troy,NaN,NaN,...,NaN,NaN,NaN,False,1.0,1.0,NaN,13.0,NaN,Katie Yezzi
1,ae78dd81-4525-4825-8981-a0f9bc301c14,ae78dd81-4525-4825-8981-a0f9bc301c14,REF8Q,Apprentice Teacher (Immediate Start SY 18-19),Teaching and Instruction,Apprentice Teacher,Apprentice Teacher,Rochester,Multi-racial,Female,...,NaN,NaN,NaN,False,2.0,6.0,9.0,12.0,1.0,Brandi Moore
2,97c1bcb8-eb94-4d19-b324-f9ce5c2ed7c0,2a787e27-f8a2-4eab-9cfd-5884a357fc15,REF93W,Receptionist (Immediate Start),School-Based Operations,School Based Operations,Receptionist,Newark,I prefer not to say,Female,...,NaN,NaN,NaN,False,NaN,1.0,21.0,NaN,NaN,Indeed

In [976]:
data.shape

(33771, 40)

Overall very few rows were not included in the dataframe after the inner join.

In [977]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33771 entries, 0 to 33770
Data columns (total 40 columns):
CANDIDATE_ID_x                                    32458 non-null object
APPLICATION_ID                                    33771 non-null object
JOB_REF_ID                                        32458 non-null object
JOB_TITLE                                         32458 non-null object
DEPARTMENT                                        32458 non-null object
POSITION_CATEGORY                                 32458 non-null object
POSITION                                          32458 non-null object
REGION                                            21590 non-null object
USI_DIVERSITY_QUESTION_RACE                       28060 non-null object
USI_DIVERSITY_QUESTION_GENDER                     27830 non-null object
USI_UNCOMMON_AFFILIATION                          28790 non-null object
USI_GPA                                           12929 non-null object
USI_TEACHER_CERT                                  8029 non-null object
USI_TEACHING_EXPERIENCE                           9786 non-null object
USI_HEARD_ABOUT_UNCOMMON                          27085 non-null object
USI_OTHER_AFFILIATION                             23210 non-null object
CANDIDATE_ID_y                                    33771 non-null object
Application Creation Date                         33771 non-null object
Job Title                                         33771 non-null object
Position                                          32486 non-null object
Position Category                                 32486 non-null object
Region                                            21602 non-null object
Grade Level                                       14618 non-null object
HO Team                                           10884 non-null object
Application Status                                33771 non-null object
Application Transfer Date                         276 non-null object
Application Status Before Rejection               29391 non-null object
Application Rejection Date                        29391 non-null object
Rejection Reason                                  26491 non-null object
Application Status Before Withdrawal              2642 non-null object
Application Withdrawal Date                       2642 non-null object
Withdrawal Reason                                 2616 non-null object
Application field: Secondary Withdrawal Reason    7 non-null object
[Unknown]                                         33771 non-null bool
Time In Application State: Lead                   4883 non-null float64
Time In Application State: New                    28820 non-null float64
Time In Application State: In-Review              22027 non-null float64
Time In Application State: Interview              2153 non-null float64
Time In Application State: Offered                374 non-null float64
Source                                            33766 non-null object
dtypes: bool(1), float64(5), object(34)
memory usage: 10.3+ MB

In [978]:
data.isnull().sum()

CANDIDATE_ID_x                                     1313
APPLICATION_ID                                        0
JOB_REF_ID                                         1313
JOB_TITLE                                          1313
DEPARTMENT                                         1313
POSITION_CATEGORY                                  1313
POSITION                                           1313
REGION                                            12181
USI_DIVERSITY_QUESTION_RACE                        5711
USI_DIVERSITY_QUESTION_GENDER                      5941
USI_UNCOMMON_AFFILIATION                           4981
USI_GPA                                           20842
USI_TEACHER_CERT                                  25742
USI_TEACHING_EXPERIENCE                           23985
USI_HEARD_ABOUT_UNCOMMON                           6686
USI_OTHER_AFFILIATION                             10561
CANDIDATE_ID_y                                        0
Application Creation Date                             0
Job Title                                             0
Position                                           1285
Position Category                                  1285
Region                                            12169
Grade Level                                       19153
HO Team                                           22887
Application Status                                    0
Application Transfer Date                         33495
Application Status Before Rejection                4380
Application Rejection Date                         4380
Rejection Reason                                   7280
Application Status Before Withdrawal              31129
Application Withdrawal Date                       31129
Withdrawal Reason                                 31155
Application field: Secondary Withdrawal Reason    33764
[Unknown]                                             0
Time In Application State: Lead                   28888
Time In Application State: New                     4951
Time In Application State: In-Review              11744
Time In Application State: Interview              31618
Time In Application State: Offered                33397
Source                                                5
dtype: int64

In [979]:
# Most missing data regarding Region is for Position Category = Home Office

### What is the content of the columns?

In [980]:
data['POSITION_CATEGORY'].unique()

array(['Student Support', 'Apprentice Teacher', 'School Based Operations',
       'Core Teacher', 'Instructional Leadership',
       'Operational Leadership', 'Specials Teacher',
       'Summer Teaching Fellows', 'Home Office', 'College Completion',
       'General Teacher', 'Regional Support Staff', nan], dtype=object)

In [981]:
data['REGION'].unique()

array(['Troy', 'Rochester', 'Newark', 'Boston', 'Camden', nan],
      dtype=object)

In [983]:
data.groupby(['REGION']).count()

,CANDIDATE_ID_x,APPLICATION_ID,JOB_REF_ID,JOB_TITLE,DEPARTMENT,POSITION_CATEGORY,POSITION,USI_DIVERSITY_QUESTION_RACE,USI_DIVERSITY_QUESTION_GENDER,USI_UNCOMMON_AFFILIATION,...,Application Withdrawal Date,Withdrawal Reason,Application field: Secondary Withdrawal Reason,[Unknown],Time In Application State: Lead,Time In Application State: New,Time In Application State: In-Review,Time In Application State: Interview,Time In Application State: Offered,Source
REGION,,,,,,,,,,,,,,,,,,,,,
Boston,3625,3625,3625,3625,3625,3625,3625,3048,3026,2997,...,143,142,0,3625,536,3194,2628,185,79,3624
Camden,3546,3546,3546,3546,3546,3546,3546,2849,2816,2871,...,367,367,0,3546,673,2990,2537,307,51,3546
Newark,9594,9594,9594,9594,9594,9594,9594,8377,8273,8476,...,791,786,1,9594,1191,8344,6603,792,121,9594
Rochester,2921,2921,2921,2921,2921,2921,2921,2488,2451,2529,...,265,263,0,2921,422,2625,1696,302,64,2921
Troy,1904,1904,1904,1904,1904,1904,1904,1747,1700,1749,...,226,224,0,1904,137,1782,1255,132,28,1903

In [984]:
data['USI_DIVERSITY_QUESTION_GENDER'].unique()

array([nan, 'Female', 'Male', 'I prefer not to say', 'Queer',
       'Gender Non-Conforming', 'Transgender', 'I prefer not to say,Male',
       'Androgynous', 'Female,I prefer not to say',
       'Female,Gender Non-Conforming', 'Female,Male', 'Androgynous,Male',
       'Male,Queer', 'Female,Queer', 'Female,Transgender'], dtype=object)

In [985]:
# We might need to do some grouping here.

In [986]:
data['USI_HEARD_ABOUT_UNCOMMON'].unique()

array([nan, 'Current or former Uncommon staff member',
       'Current or Former Uncommon Staff Member', 'Uncommon Website',
       'LinkedIn, Indeed, or The Muse',
       'Current or former Uncommon staff member,Uncommon Schools Recruiter',
       'Uncommon Schools Recruiter',
       'Glassdoor,LinkedIn, Indeed, or The Muse,Uncommon Website',
       'Google Search,LinkedIn', 'Google Search', 'Other Job Fair',
       'Facebook, Instagram, or Twitter,Glassdoor,LinkedIn, Indeed, or The Muse',
       'Other Job Board', 'Glassdoor,LinkedIn, Indeed, or The Muse',
       'Current or former Uncommon staff member,Former Summer Teaching Fellow,Google Search,Uncommon Website',
       'Glassdoor', 'Online Advertisement',
       'Google Search,Uncommon Website', 'Event, Panel, or Career Fair',
       'Event, Panel, or Career Fair,Newsletter, Article, or Publication',
       'LinkedIn, Indeed, or The Muse,Uncommon Website',
       'Current or Former Uncommon Staff Member,Newsletter, Article, or Publication',
       'Facebook, Instagram, or Twitter,LinkedIn, Indeed, or The Muse,Other Job Board,Uncommon Website',
       'LinkedIn, Indeed, or The Muse,Other Job Board,Uncommon Website',
       'Current or Former Uncommon Staff Member,Uncommon Website',
       'Facebook, Instagram, or Twitter',
       'Current or Former Uncommon Staff Member,Event, Panel, or Career Fair,LinkedIn, Indeed, or The Muse',
       'Glassdoor,LinkedIn, Indeed, or The Muse,Other Job Board',
       'Indeed',
       'Current or Former Uncommon Staff Member,Newsletter, Article, or Publication,Uncommon Website',
       'Current or Former Uncommon Staff Member,LinkedIn, Indeed, or The Muse',
       'Current or Former Uncommon Staff Member,LinkedIn, Indeed, or The Muse,Other Job Board,Uncommon Website',
       'Event, Panel, or Career Fair,Other Job Board',
       'Event, Panel, or Career Fair,LinkedIn, Indeed, or The Muse,Uncommon Schools Recruiter',
       'Facebook, Instagram, or Twitter,LinkedIn, Indeed, or The Muse,Uncommon Website',
       'Google Search,Other Job Board',
       'Newsletter, Article, or Publication,Uncommon Website',
       'University Job Fair or Career Center',
       'Other Job Board,Uncommon Schools Recruiter',
       'LinkedIn, Indeed, or The Muse,Other Job Board', 'LinkedIn',
       'Other Job Board,Uncommon Website',
       'Uncommon Schools Recruiter,Uncommon Website',
       'Event, Panel, or Career Fair,University Job Fair or Career Center',
       'Glassdoor,Uncommon Website',
       'Current or Former Uncommon Staff Member,Event, Panel, or Career Fair,Uncommon Website',
       'Current or Former Uncommon Staff Member,Event, Panel, or Career Fair,LinkedIn, Indeed, or The Muse,Uncommon Schools Recruiter',
       'Current or Former Uncommon Staff Member,LinkedIn, Indeed, or The Muse,Uncommon Website',
       'LinkedIn, Indeed, or The Muse,Uncommon Schools Recruiter,Uncommon Website',
       'Event, Panel, or Career Fair,LinkedIn, Indeed, or The Muse,Uncommon Website',
       'Glassdoor,Other Job Board', 'Newsletter, Article, or Publication',
       'Newsletter, Article, or Publication,Other Job Board',
       'Current or Former Uncommon Staff Member,Glassdoor,Uncommon Schools Recruiter',
       'Facebook, Instagram, or Twitter,LinkedIn, Indeed, or The Muse',
       'Glassdoor,LinkedIn, Indeed, or The Muse,Uncommon Schools Recruiter',
       'Current or Former Uncommon Staff Member,Glassdoor,Other Job Board,Uncommon Website',
       'Facebook, Instagram, or Twitter,Other Job Board,Uncommon Website',
       'Facebook,Former Summer Teaching Fellow',
       'Current or former Uncommon staff member,Other Job Board',
       'Current or Former Uncommon Staff Member,Glassdoor',
       'Current or Former Uncommon Staff Member,Other Job Board',
       'Facebook, Instagram, or Twitter,Glassdoor',
       'Current or Former Uncommon Staff Member,Event, Panel, or Career Fair',
       'Online Advertisement,Uncommon Schools Recruiter',
       'Current or former Uncommon staff member,Indeed,LinkedIn,News Articles,Teaching Publication (Teach Like a Champion, Leverage Leadership,etc.),Uncommon Website',
       'LinkedIn, Indeed, or The Muse,Online Advertisement',
       'Current or Former Uncommon Staff Member,Event, Panel, or Career Fair,Glassdoor,LinkedIn, Indeed, or The Muse,Uncommon Website',
       'Google Search,Indeed,Online Advertisement,Uncommon Website',
       'Event, Panel, or Career Fair,Facebook, Instagram, or Twitter,LinkedIn, Indeed, or The Muse,Newsletter, Article, or Publication',
       'Current or former Uncommon staff member,Google Search,Uncommon Website',
       'Event, Panel, or Career Fair,Other Job Board,Uncommon Schools Recruiter,Uncommon Website',
       'Current or former Uncommon staff member,Glassdoor,LinkedIn',
       'Facebook, Instagram, or Twitter,Glassdoor,Other Job Board',
       'Current or Former Uncommon Staff Member,Event, Panel, or Career Fair,Uncommon Schools Recruiter',
       'Event or Panel',
       'Facebook, Instagram, or Twitter,LinkedIn, Indeed, or The Muse,Newsletter, Article, or Publication,Other Job Board,Uncommon Website',
       'Teaching Publication (Teach Like a Champion, Leverage Leadership,etc.)',
       'LinkedIn, Indeed, or The Muse,Newsletter, Article, or Publication,Uncommon Website',
       'LinkedIn, Indeed, or The Muse,Newsletter, Article, or Publication',
       'Indeed,LinkedIn,Uncommon Website',
       'Event, Panel, or Career Fair,Facebook, Instagram, or Twitter,Glassdoor,LinkedIn, Indeed, or The Muse,Other Job Board',
       'Event, Panel, or Career Fair,Newsletter, Article, or Publication,Uncommon Website',
       'Event, Panel, or Career Fair,LinkedIn, Indeed, or The Muse,Newsletter, Article, or Publication',
       'Facebook,Glassdoor',
       'Current or Former Uncommon Staff Member,Facebook, Instagram, or Twitter,LinkedIn, Indeed, or The Muse',
       'Event, Panel, or Career Fair,Facebook, Instagram, or Twitter,Uncommon Website',
       'Google Search,Online Advertisement',
       'LinkedIn, Indeed, or The Muse,Newsletter, Article, or Publication,Other Job Board',
       'Current or Former Uncommon Staff Member,Event, Panel, or Career Fair,Facebook, Instagram, or Twitter,Glassdoor,LinkedIn, Indeed, or The Muse,Newsletter, Article, or Publication,Uncommon Website',
       'Facebook, Instagram, or Twitter,Glassdoor,LinkedIn, Indeed, or The Muse,Uncommon Website',
       'Current or Former Uncommon Staff Member,Event, Panel, or Career Fair,Facebook, Instagram, or Twitter,Newsletter, Article, or Publication,Other Job Board,Uncommon Website',
       'Facebook, Instagram, or Twitter,Uncommon Website',
       'Event, Panel, or Career Fair,Facebook, Instagram, or Twitter,Glassdoor,LinkedIn, Indeed, or The Muse,Uncommon Schools Recruiter,Uncommon Website',
       'Event, Panel, or Career Fair,Uncommon Website',
       'Facebook, Instagram, or Twitter,LinkedIn, Indeed, or The Muse,Uncommon Schools Recruiter,Uncommon Website',
       'Facebook,Google Search,Indeed',
       'Event, Panel, or Career Fair,Facebook, Instagram, or Twitter,Glassdoor,LinkedIn, Indeed, or The Muse',
       'Current or Former Uncommon Staff Member,Uncommon Schools Recruiter',
       'Event, Panel, or Career Fair,LinkedIn, Indeed, or The Muse',
       'Other Job Board,University Job Fair or Career Center', 'The Muse',
       'Current or Former Uncommon Staff Member,Facebook, Instagram, or Twitter,Glassdoor,LinkedIn, Indeed, or The Muse,Newsletter, Article, or Publication,Other Job Board,Uncommon Schools Recruiter,Uncommon Website',
       'LinkedIn, Indeed, or The Muse,Uncommon Schools Recruiter',
       'Event, Panel, or Career Fair,Glassdoor,LinkedIn, Indeed, or The Muse',
       'LinkedIn,News Articles',
       'Event, Panel, or Career Fair,LinkedIn, Indeed, or The Muse,Other Job Board,Uncommon Website',
       'Current or Former Uncommon Staff Member,Event, Panel, or Career Fair,LinkedIn, Indeed, or The Muse,Uncommon Website',
       'Glassdoor,Newsletter, Article, or Publication',
       'Current or former Uncommon staff member,LinkedIn, Indeed, or The Muse',
       'Glassdoor,Newsletter, Article, or Publication,Uncommon Schools Recruiter,Uncommon Website',
       'Facebook, Instagram, or Twitter,LinkedIn, Indeed, or The Muse,Other Job Board',
       'Event, Panel, or Career Fair,LinkedIn, Indeed, or The Muse,Other Job Board',
       'LinkedIn,Uncommon Website',
       'Glassdoor,Uncommon Schools Recruiter,Uncommon Website',
       'Facebook, Instagram, or Twitter,Newsletter, Article, or Publication,Uncommon Website',
       'Event, Panel, or Career Fair,Uncommon Schools Recruiter,Uncommon Website',
       'Current or Former Uncommon Staff Member,Event, Panel, or Career Fair,Newsletter, Article, or Publication,Other Job Board,Uncommon Schools Recruiter,Uncommon Website',
       'Google Search,Indeed',
       'Current or former Uncommon staff member,LinkedIn',
       'Event, Panel, or Career Fair,Facebook, Instagram, or Twitter,LinkedIn, Indeed, or The Muse,Other Job Board,Uncommon Website',
       'Current or Former Uncommon Staff Member,Other Job Board,Uncommon Website',
       'Event, Panel, or Career Fair,Other Job Board,Uncommon Website',
       'Current or Former Uncommon Staff Member,Event, Panel, or Career Fair,Glassdoor,LinkedIn, Indeed, or The Muse,Uncommon Schools Recruiter,Uncommon Website',
       'Event, Panel, or Career Fair,Glassdoor',
       'Event, Panel, or Career Fair,Facebook, Instagram, or Twitter,LinkedIn, Indeed, or The Muse,Uncommon Website',
       'Indeed,LinkedIn, Indeed, or The Muse',
       'Indeed,Online Advertisement',
       'Current or Former Uncommon Staff Member,Uncommon Schools Recruiter,Uncommon Website',
       'Event, Panel, or Career Fair,Facebook, Instagram, or Twitter,LinkedIn, Indeed, or The Muse,Newsletter, Article, or Publication,Uncommon Website',
       'Event, Panel, or Career Fair,Facebook, Instagram, or Twitter,LinkedIn, Indeed, or The Muse,Uncommon Schools Recruiter,Uncommon Website',
       'Former Summer Teaching Fellow,Google Search,Indeed,Online Advertisement',
       'Current or Former Uncommon Staff Member,LinkedIn, Indeed, or The Muse,Uncommon Schools Recruiter',
       'Glassdoor,Other Job Board,Uncommon Website',
       'Event, Panel, or Career Fair,Glassdoor,LinkedIn, Indeed, or The Muse,Uncommon Website',
       'Teaching Publication (Teach Like a Champion, Leverage Leadership,etc.),Uncommon Schools Recruiter',
       'Facebook, Instagram, or Twitter,Glassdoor,LinkedIn, Indeed, or The Muse,Newsletter, Article, or Publication,Uncommon Website',
       'Glassdoor,LinkedIn, Indeed, or The Muse,Other Job Board,Uncommon Website',
       'Facebook, Instagram, or Twitter,Glassdoor,LinkedIn, Indeed, or The Muse,Other Job Board,Uncommon Website',
       'Event, Panel, or Career Fair,Facebook, Instagram, or Twitter,Uncommon Schools Recruiter,Uncommon Website',
       'Facebook, Instagram, or Twitter,Glassdoor,LinkedIn, Indeed, or The Muse,Newsletter, Article, or Publication,Other Job Board,Uncommon Website',
       'Facebook, Instagram, or Twitter,Newsletter, Article, or Publication,Other Job Board,Uncommon Website',
       'Indeed,LinkedIn,Online Advertisement',
       'Current or Former Uncommon Staff Member,Glassdoor,Uncommon Website',
       'Event, Panel, or Career Fair,Facebook, Instagram, or Twitter,LinkedIn, Indeed, or The Muse,Other Job Board',
       'Facebook, Instagram, or Twitter,Glassdoor,LinkedIn, Indeed, or The Muse,Newsletter, Article, or Publication',
       'Event, Panel, or Career Fair,Facebook, Instagram, or Twitter',
       'Current or Former Uncommon Staff Member,Event, Panel, or Career Fair,Other Job Board',
       'Current or Former Uncommon Staff Member,Facebook, Instagram, or Twitter,Glassdoor,LinkedIn, Indeed, or The Muse,Uncommon Website',
       'Current or Former Uncommon Staff Member,LinkedIn, Indeed, or The Muse,Newsletter, Article, or Publication,Uncommon Schools Recruiter,Uncommon Website',
       'Uncommon Website,University Job Fair or Career Center',
       'Facebook, Instagram, or Twitter,Glassdoor,LinkedIn, Indeed, or The Muse,Newsletter, Article, or Publication,Uncommon Schools Recruiter,Uncommon Website',
       'Event or Panel,Uncommon Schools Recruiter',
       'Glassdoor,LinkedIn, Indeed, or The Muse,Other Job Board,Uncommon Schools Recruiter',
       'Current or Former Uncommon Staff Member,Facebook, Instagram, or Twitter,LinkedIn, Indeed, or The Muse,Uncommon Website',
       'Google Search,Indeed,Uncommon Website',
       'Event, Panel, or Career Fair,Uncommon Schools Recruiter',
       'Current or former Uncommon staff member,Event or Panel,News Articles,Teaching Publication (Teach Like a Champion, Leverage Leadership,etc.)',
       'Glassdoor,LinkedIn, Indeed, or The Muse,Newsletter, Article, or Publication,Uncommon Website',
       'Facebook, Instagram, or Twitter,Other Job Board',
       'Glassdoor,Indeed',
       'Glassdoor,Newsletter, Article, or Publication,Other Job Board',
       'Current or Former Uncommon Staff Member,LinkedIn, Indeed, or The Muse,Uncommon Schools Recruiter,Uncommon Website',
       'Email blast',
       'Event, Panel, or Career Fair,Glassdoor,LinkedIn, Indeed, or The Muse,Other Job Board,Uncommon Website',
       'Event, Panel, or Career Fair,Facebook, Instagram, or Twitter,LinkedIn, Indeed, or The Muse',
       'Event or Panel,Uncommon Website',
       'Event, Panel, or Career Fair,LinkedIn, Indeed, or The Muse,Uncommon Schools Recruiter,Uncommon Website',
       'Current or Former Uncommon Staff Member,Facebook, Instagram, or Twitter,Uncommon Website',
       'Current or former Uncommon staff member,Google Search,LinkedIn',
       'Event, Panel, or Career Fair,Facebook, Instagram, or Twitter,Newsletter, Article, or Publication,Other Job Board,Uncommon Schools Recruiter,Uncommon Website',
       'LinkedIn, Indeed, or The Muse,Newsletter, Article, or Publication,Other Job Board,Uncommon Website',
       'Current or Former Uncommon Staff Member,Facebook, Instagram, or Twitter,Glassdoor,Uncommon Website',
       'Current or Former Uncommon Staff Member,Event, Panel, or Career Fair,Facebook, Instagram, or Twitter,Uncommon Website',
       'Facebook, Instagram, or Twitter,Glassdoor,LinkedIn, Indeed, or The Muse,Newsletter, Article, or Publication,Other Job Board',
       'Facebook, Instagram, or Twitter,Newsletter, Article, or Publication,Other Job Board',
       'Event, Panel, or Career Fair,Newsletter, Article, or Publication,Other Job Board,Uncommon Website',
       'Other Job Board,Uncommon Schools Recruiter,Uncommon Website',
       'Facebook, Instagram, or Twitter,LinkedIn, Indeed, or The Muse,Newsletter, Article, or Publication',
       'Google Search,Online Advertisement,Uncommon Website',
       'Current or Former Uncommon Staff Member,Glassdoor,LinkedIn, Indeed, or The Muse,Uncommon Website',
       'Current or Former Uncommon Staff Member,Glassdoor,LinkedIn, Indeed, or The Muse,Other Job Board,Uncommon Website',
       'Uncommon Schools Recruiter,University Job Fair or Career Center',
       'Current or former Uncommon staff member,Indeed',
       'Glassdoor,LinkedIn, Indeed, or The Muse,Newsletter, Article, or Publication',
       'Indeed,LinkedIn',
       'Facebook,Indeed,News Articles,Uncommon Website', 'News Articles',
       'Event, Panel, or Career Fair,Glassdoor,LinkedIn, Indeed, or The Muse,Uncommon Schools Recruiter,Uncommon Website',
       'Uncommon Student or Parent',
       'LinkedIn, Indeed, or The Muse,Other Job Board,Uncommon Schools Recruiter',
       'Indeed,Uncommon Schools Recruiter,Uncommon Website',
       'Facebook, Instagram, or Twitter,LinkedIn, Indeed, or The Muse,Newsletter, Article, or Publication,Uncommon Website',
       'Current or Former Uncommon Staff Member,Event, Panel, or Career Fair,Facebook, Instagram, or Twitter,Newsletter, Article, or Publication,Uncommon Schools Recruiter,Uncommon Website',
       'Current or former Uncommon staff member,Facebook,Indeed,Uncommon Website',
       'Current or Former Uncommon Staff Member,Newsletter, Article, or Publication,Other Job Board',
       'Indeed,Online Advertisement,Teaching Publication (Teach Like a Champion, Leverage Leadership,etc.),Uncommon Website',
       'Event, Panel, or Career Fair,Glassdoor,Newsletter, Article, or Publication,Other Job Board,Uncommon Schools Recruiter,Uncommon Website',
       'Current or Former Uncommon Staff Member,LinkedIn, Indeed, or The Muse,Newsletter, Article, or Publication,Other Job Board,Uncommon Website',
       'Google Search,LinkedIn,The Muse',
       'Glassdoor,LinkedIn, Indeed, or The Muse,Uncommon Schools Recruiter,Uncommon Website',
       'Facebook, Instagram, or Twitter,Uncommon Schools Recruiter,Uncommon Website',
       'Glassdoor,Newsletter, Article, or Publication,Uncommon Website',
       'Glassdoor,Other Job Board,Uncommon Schools Recruiter,Uncommon Website',
       'Current or Former Uncommon Staff Member,LinkedIn, Indeed, or The Muse,Other Job Board',
       'Current or Former Uncommon Staff Member,Newsletter, Article, or Publication,Uncommon Schools Recruiter,Uncommon Website',
       'Current or Former Uncommon Staff Member,Event, Panel, or Career Fair,Newsletter, Article, or Publication,Uncommon Website',
       'Newsletter, Article, or Publication,Uncommon Schools Recruiter,Uncommon Website',
       'Current or Former Uncommon Staff Member,Event, Panel, or Career Fair,LinkedIn, Indeed, or The Muse,Newsletter, Article, or Publication,Uncommon Website',
       'Current or former Uncommon staff member,Indeed,LinkedIn,Uncommon Website',
       'Current or Former Uncommon Staff Member,Glassdoor,LinkedIn, Indeed, or The Muse',
       'LinkedIn, Indeed, or The Muse,Newsletter, Article, or Publication,Other Job Board,Uncommon Schools Recruiter,Uncommon Website',
       'Facebook, Instagram, or Twitter,Newsletter, Article, or Publication',
       'Current or Former Uncommon Staff Member,Event, Panel, or Career Fair,Facebook, Instagram, or Twitter,LinkedIn, Indeed, or The Muse,Other Job Board,Uncommon Website',
       'Current or Former Uncommon Staff Member,Event, Panel, or Career Fair,Newsletter, Article, or Publication',
       'LinkedIn,LinkedIn, Indeed, or The Muse,Uncommon Schools Recruiter,Uncommon Student or Parent,Uncommon Website',
       'Email blast,Google Search,Indeed,LinkedIn,Online Advertisement,Other Job Fair,Uncommon Website',
       'Google Search,Online Advertisement,Uncommon Website,University Job Fair or Career Center',
       'Newsletter, Article, or Publication,Other Job Board,Uncommon Website',
       'Current or Former Uncommon Staff Member,Event, Panel, or Career Fair,Glassdoor,LinkedIn, Indeed, or The Muse',
       'Event or Panel,Indeed,Newsletter,Teaching Publication (Teach Like a Champion, Leverage Leadership,etc.)',
       'Glassdoor,Other Job Board,Uncommon Schools Recruiter',
       'Event, Panel, or Career Fair,Facebook, Instagram, or Twitter,LinkedIn, Indeed, or The Muse,Other Job Board,Uncommon Schools Recruiter,Uncommon Website',
       'LinkedIn, Indeed, or The Muse,Other Job Board,Uncommon Schools Recruiter,Uncommon Website',
       'Facebook, Instagram, or Twitter,Uncommon Schools Recruiter',
       'Current or former Uncommon staff member,Google Search,Indeed',
       'Online Advertisement,Uncommon Website',
       'Event, Panel, or Career Fair,Glassdoor,Uncommon Website',
       'Current or Former Uncommon Staff Member,Event, Panel, or Career Fair,Facebook, Instagram, or Twitter,LinkedIn, Indeed, or The Muse',
       'Current or Former Uncommon Staff Member,Event, Panel, or Career Fair,Facebook, Instagram, or Twitter,LinkedIn, Indeed, or The Muse,Uncommon Schools Recruiter,Uncommon Website',
       'Current or Former Uncommon Staff Member,Event, Panel, or Career Fair,LinkedIn, Indeed, or The Muse,Uncommon Schools Recruiter,Uncommon Website',
       'Indeed,Uncommon Website',

In [987]:
## This need som serious work if we are going to be able to use it.
## Here I would prefer to have the question maybe phrased to how did you primarily hear about this employer? 
## And then you can only choose one (or max 2) options
## Sometimes less in more. To get to much options

In [988]:
data['Application Creation Date'].head()

0    2019-04-23T19:31:27
1    2019-01-23T19:18:44
2    2019-05-30T15:51:49
3    2019-01-25T20:56:51
4    2019-04-22T22:40:27
Name: Application Creation Date, dtype: object

In [989]:
# remove time stamp
data['Application Creation Date'] = data['Application Creation Date'].str.slice(stop=10)

data['Application Creation Date'].head()

0    2019-04-23
1    2019-01-23
2    2019-05-30
3    2019-01-25
4    2019-04-22
Name: Application Creation Date, dtype: object

In [990]:
# convert into datetime format
data['Application Creation Date'] = pd.to_datetime(data['Application Creation Date'])
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33771 entries, 0 to 33770
Data columns (total 40 columns):
CANDIDATE_ID_x                                    32458 non-null object
APPLICATION_ID                                    33771 non-null object
JOB_REF_ID                                        32458 non-null object
JOB_TITLE                                         32458 non-null object
DEPARTMENT                                        32458 non-null object
POSITION_CATEGORY                                 32458 non-null object
POSITION                                          32458 non-null object
REGION                                            21590 non-null object
USI_DIVERSITY_QUESTION_RACE                       28060 non-null object
USI_DIVERSITY_QUESTION_GENDER                     27830 non-null object
USI_UNCOMMON_AFFILIATION                          28790 non-null object
USI_GPA                                           12929 non-null object
USI_TEACHER_CERT                                  8029 non-null object
USI_TEACHING_EXPERIENCE                           9786 non-null object
USI_HEARD_ABOUT_UNCOMMON                          27085 non-null object
USI_OTHER_AFFILIATION                             23210 non-null object
CANDIDATE_ID_y                                    33771 non-null object
Application Creation Date                         33771 non-null datetime64[ns]
Job Title                                         33771 non-null object
Position                                          32486 non-null object
Position Category                                 32486 non-null object
Region                                            21602 non-null object
Grade Level                                       14618 non-null object
HO Team                                           10884 non-null object
Application Status                                33771 non-null object
Application Transfer Date                         276 non-null object
Application Status Before Rejection               29391 non-null object
Application Rejection Date                        29391 non-null object
Rejection Reason                                  26491 non-null object
Application Status Before Withdrawal              2642 non-null object
Application Withdrawal Date                       2642 non-null object
Withdrawal Reason                                 2616 non-null object
Application field: Secondary Withdrawal Reason    7 non-null object
[Unknown]                                         33771 non-null bool
Time In Application State: Lead                   4883 non-null float64
Time In Application State: New                    28820 non-null float64
Time In Application State: In-Review              22027 non-null float64
Time In Application State: Interview              2153 non-null float64
Time In Application State: Offered                374 non-null float64
Source                                            33766 non-null object
dtypes: bool(1), datetime64[ns](1), float64(5), object(33)
memory usage: 10.3+ MB

In [991]:
# new column for month
data['Application Creation Month'] = data['Application Creation Date'] .map(lambda x: x.month)
data.head()

,CANDIDATE_ID_x,APPLICATION_ID,JOB_REF_ID,JOB_TITLE,DEPARTMENT,POSITION_CATEGORY,POSITION,REGION,USI_DIVERSITY_QUESTION_RACE,USI_DIVERSITY_QUESTION_GENDER,...,Withdrawal Reason,Application field: Secondary Withdrawal Reason,[Unknown],Time In Application State: Lead,Time In Application State: New,Time In Application State: In-Review,Time In Application State: Interview,Time In Application State: Offered,Source,Application Creation Month
0,e9263572-f945-4e2e-bf66-6ae0c25c56f5,f72b1b7e-f35f-4f2a-aa79-cb29c8ff73e6,REF13L,Dean of Students,Student Services,Student Support,Dean Of Students,Troy,NaN,NaN,...,NaN,NaN,False,1.0,1.0,NaN,13.0,NaN,Katie Yezzi,4
1,ae78dd81-4525-4825-8981-a0f9bc301c14,ae78dd81-4525-4825-8981-a0f9bc301c14,REF8Q,Apprentice Teacher (Immediate Start SY 18-19),Teaching and Instruction,Apprentice Teacher,Apprentice Teacher,Rochester,Multi-racial,Female,...,NaN,NaN,False,2.0,6.0,9.0,12.0,1.0,Brandi Moore,1
2,97c1bcb8-eb94-4d19-b324-f9ce5c2ed7c0,2a787e27-f8a2-4eab-9cfd-5884a357fc15,REF93W,Receptionist (Immediate Start),School-Based Operations,School Based Operations,Receptionist,Newark,I prefer not to say,Female,...,NaN,NaN,False,NaN,1.0,21.0,NaN,NaN,Indeed,5
3,da86deae-b261-47fb-b0c4-5376d7c96165,12c98f63-49f8-4642-b4de-ecc78d99036a,REF20F,Elementary Teacher (Immediate Start),Teaching and Instruction,Core Teacher,Elementary School Teacher,Newark,NaN,NaN,...,NaN,NaN,False,1.0,1.0,8.0,7.0,1.0,Default Career Page,1
4,6233f272-d866-4927-b901-8bab73213a29,6233f272-d866-4927-b901-8bab73213a29,REF52A,Middle School ELA Teacher (Immediate Start),Teaching and Instruction,Core Teacher,MS ELA Teacher,Boston,White,Female,...,NaN,NaN,False,NaN,3.0,2.0,11.0,13.0,RoxburyPrep Jobs,4

## Analysing

### Number of Jobpostings and Applications in April 2019 for Newark

#### Month = April

In [992]:
data_april = data[data['Application Creation Month'] == 4]

data_april.head()

,CANDIDATE_ID_x,APPLICATION_ID,JOB_REF_ID,JOB_TITLE,DEPARTMENT,POSITION_CATEGORY,POSITION,REGION,USI_DIVERSITY_QUESTION_RACE,USI_DIVERSITY_QUESTION_GENDER,...,Withdrawal Reason,Application field: Secondary Withdrawal Reason,[Unknown],Time In Application State: Lead,Time In Application State: New,Time In Application State: In-Review,Time In Application State: Interview,Time In Application State: Offered,Source,Application Creation Month
0,e9263572-f945-4e2e-bf66-6ae0c25c56f5,f72b1b7e-f35f-4f2a-aa79-cb29c8ff73e6,REF13L,Dean of Students,Student Services,Student Support,Dean Of Students,Troy,NaN,NaN,...,NaN,NaN,False,1.0,1.0,NaN,13.0,NaN,Katie Yezzi,4
4,6233f272-d866-4927-b901-8bab73213a29,6233f272-d866-4927-b901-8bab73213a29,REF52A,Middle School ELA Teacher (Immediate Start),Teaching and Instruction,Core Teacher,MS ELA Teacher,Boston,White,Female,...,NaN,NaN,False,NaN,3.0,2.0,11.0,13.0,RoxburyPrep Jobs,4
22,39f00a50-7902-4a7c-9c6c-ba6228e8c3d5,538d93b0-4f0d-4266-a0db-77c26c4d5f33,REF56L,Middle School History Teacher (Immediate Start),Teaching and Instruction,Core Teacher,MS History Teacher,Rochester,NaN,NaN,...,NaN,NaN,False,1.0,1.0,NaN,NaN,NaN,Default Career Page,4
33,855ae3f9-30b8-4b1c-b562-f012cc91a7be,855ae3f9-30b8-4b1c-b562-f012cc91a7be,REF77R,Office Manager (Immediate Start),School-Based Operations,School Based Operations,Office Manager,Newark,Black or African American,Female,...,NaN,NaN,False,NaN,1.0,4.0,65.0,NaN,IndeedPro,4
38,5b7ed540-6f96-473f-96e4-80f476ea9f6d,c454c05d-c2f1-4716-bc67-768d78a592ab,REF32M,High School History Teacher (Immediate Start S...,Teaching and Instruction,Core Teacher,HS History Teacher,Troy,White,Female,...,NaN,NaN,False,NaN,1.0,7.0,22.0,NaN,IndeedPro,4

In [993]:
data_april.shape

(4658, 41)

Number of applications in April = 4658

In [994]:
data_april['JOB_TITLE'].nunique()

98

Number of postings in April = 98

In [995]:
data_april['JOB_TITLE'].unique()

array(['Dean of Students', 'Middle School ELA Teacher (Immediate Start)',
       'Middle School History Teacher (Immediate Start)',
       'Office Manager (Immediate Start)',
       'High School History Teacher (Immediate Start SY 18-19)',
       'Middle School Science Teacher SY 19-20) - DO NOT USE',
       'Elementary Teacher (Immediate Start)',
       'High School Director of Operations',
       'Special Projects Coordinator (Immediate Start)', 'TEST JOB',
       'Operations Fellow', 'Elementary Teacher (SY 19-20) - Do Not Use',
       'Social Worker (Immediate Start SY 18-19)',
       'Apprentice Teacher (Immediate Start SY 18-19)', 'Relay Resident',
       'Executive Assistant to the CFO',
       'Behavior Support Specialist (Immediate Start SY 18-19)',
       'Director of Operations',
       'Senior Associate Director of College Completion',
       'Operations Coordinator', 'College Counselor (Immediate Start)',
       'Special Education Teacher (Immediate Start)',
       'Occupational Therapist', 'Apprentice Teacher (Immediate Start)',
       'Associate/Senior Associate Director of Literacy, 5-8',
       'Dean of Students (Immediate Start)',
       'High School ELA Teacher (Immediate Start)',
       'Senior Associate Director of IT, Support (Tier 1 Manager)',
       'K-8 Teacher - Elementary and Middle School Teacher (Immediate Start)',
       'High School Spanish Teacher (Immediate Start)',
       'K-12 Teacher - Elementary, Middle, High School Teacher (Immediate Start)',
       'Special Education Coordinator (Immediate Start SY 18-19)',
       'Elementary Teacher (Immediate Start SY 18-19)',
       'Business Analyst', 'General Maintenance Worker', 'Grant Writer',
       'Senior Associate Director of School Management',
       'Operations Fellow (Immediate Start SY 18-19)', 'School Principal',
       'High School Math Teacher (Immediate Start)',
       '5-12 Teacher - Middle, High School Teacher (Immediate Start)',
       'Dean of Students (Immediate Start SY 18-19)',
       'Special Assistant to the CEO', 'Director of Development',
       'Director of Strategy & Operations',
       'Student Recruitment Coordinator (Immediate Start)',
       'Director of Special Projects (Immediate Start)',
       'Special Education Teacher (Immediate Start SY 18-19)',
       'Social Worker (Immediate Start)',
       'Senior Associate Director of Operations',
       'Regional Director of Special Projects',
       'Director of Special Projects',
       'High School Dean of Curriculum & Instruction (Immediate Start)',
       'Middle School History Teacher (Immediate Start SY 18-19)',
       'Director of Real Estate & Facilities (Senior Project Manager)',
       'Senior Director of Strategy & Operations for Special Education (SPED)',
       'High School History Teacher (Immediate Start)',
       'Middle School Science Teacher (Immediate Start)',
       'Elementary Performing Arts Teacher (Immediate Start)',
       'Summer Teaching Fellow 2019', 'Behavior Support Specialist',
       'Regional Director of Facilities', 'Principal Fellow',
       'Elementary Special Education Resource Replacement Teacher (Immediate Start SY 18-19)',
       'Middle School  Performing Arts Teacher (Immediate Start)',
       'High School Spanish Teacher (Immediate Start SY 18-19)',
       'Speech and Language Pathologist (Immediate Start)',
       'High School History Teacher',
       'Senior Associate Director of IT, Support (SIS Product Owner)',
       'High School Science Teacher (Immediate Start)',
       'Technical Program Manager (Innovation Fellow at Uncommon Schools)',
       'Professional Development Writer',
       'Middle School Spanish Teacher (Immediate Start)',
       'High School Math Teacher (Immediate Start SY 18-19)',
       'Middle School Special Education Teacher (Immediate Start)',
       'Middle School Math Teacher (Immediate Start)',
       'Middle School PE Teacher (Immediate Start SY 18-19)',
       'Associate Chief Operating Officer',
       'Middle School PE Teacher (Immediate Start)',
       'Special Education Coordinator (Immediate Start)',
       'Teacher Assistant (Immediate Start)',
       'Middle School Special Education Teacher (Immediate Start SY 18-19)',
       '5-12 ESL Teacher (Immediate Start)', 'Associate Dean of Students',
       'High School  Performing Arts Teacher (Immediate Start)',
       'Special Projects Coordinator (Immediate Start SY 18-19)',
       'Performing Arts Teacher (Immediate Start)',
       'Middle School Math Teacher (Immediate Start SY 18-19)',
       'Dean of Curriculum & Instruction',
       'Chief of Staff to the Chief Schools Officer, K-8',
       'Onsite Facility Manager',
       'Dean of Students (SY 19-20) - Do Not Use',
       'Middle School History Teacher',
       'Middle School ELA Teacher (Immediate Start SY 18-19)',
       'High School ELA Teacher (SY 19-20)  - DO NOT USE',
       'Principal Fellow (Immediate Start SY 18-19)',
       'High School Science Teacher',
       'High School Computer Science Teacher (Immediate Start SY 18-19)',
       nan], dtype=object)

Some job titels were labled with DO NOT USE, but there are applications on the positions. So it's in the statistics.

In [1096]:
data_april.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4658 entries, 0 to 33757
Data columns (total 55 columns):
CANDIDATE_ID_x                                    4504 non-null object
APPLICATION_ID                                    4658 non-null object
JOB_REF_ID                                        4504 non-null object
JOB_TITLE                                         4504 non-null object
DEPARTMENT                                        4504 non-null object
POSITION_CATEGORY                                 4504 non-null object
POSITION                                          4504 non-null object
REGION                                            3048 non-null object
USI_DIVERSITY_QUESTION_RACE                       3545 non-null object
USI_DIVERSITY_QUESTION_GENDER                     3509 non-null object
USI_UNCOMMON_AFFILIATION                          3663 non-null object
USI_GPA                                           1633 non-null object
USI_TEACHER_CERT                                  889 non-null object
USI_TEACHING_EXPERIENCE                           1108 non-null object
USI_HEARD_ABOUT_UNCOMMON                          3402 non-null object
USI_OTHER_AFFILIATION                             3260 non-null object
CANDIDATE_ID_y                                    4658 non-null object
Application Creation Date                         4658 non-null datetime64[ns]
Job Title                                         4658 non-null object
Position                                          4504 non-null object
Position Category                                 4504 non-null object
Region                                            3048 non-null object
Grade Level                                       1885 non-null object
HO Team                                           1456 non-null object
Application Status                                4658 non-null object
Application Transfer Date                         35 non-null object
Application Status Before Rejection               4151 non-null object
Application Rejection Date                        4151 non-null object
Rejection Reason                                  3478 non-null object
Application Status Before Withdrawal              392 non-null object
Application Withdrawal Date                       392 non-null object
Withdrawal Reason                                 391 non-null object
Application field: Secondary Withdrawal Reason    0 non-null object
[Unknown]                                         4658 non-null bool
Time In Application State: Lead                   4658 non-null float64
Time In Application State: New                    4658 non-null float64
Time In Application State: In-Review              4658 non-null float64
Time In Application State: Interview              4658 non-null float64
Time In Application State: Offered                4658 non-null float64
Source                                            4658 non-null object
Application Creation Month                        4658 non-null int64
num_applications                                  4658 non-null int64
HIRED                                             4658 non-null uint8
INTERVIEW/Interview 1                             4658 non-null uint8
INTERVIEW/ON Hold: Pre-Interview                  4658 non-null uint8
INTERVIEW/On Hold: Pre Interview                  4658 non-null uint8
INTERVIEW/On Hold: Pre-interview                  4658 non-null uint8
INTERVIEW/Ready for Mgr Review                    4658 non-null uint8
IN_REVIEW/Application Review                      4658 non-null uint8
IN_REVIEW/ON HOLD: PRE-SCREEN                     4658 non-null uint8
IN_REVIEW/On Hold: Pre Screen                     4658 non-null uint8
REJECTED                                          4658 non-null uint8
TRANSFERRED                                       4658 non-null uint8
WITHDRAWN                                         4658 non-null uint8
Time In Application Process                       4658 non-null float64
dtypes: bool(1), datetime64[ns](1), float64(6), int64(2), object(33), uint8(12)
memory usage: 1.7+ MB

In [1097]:
data_april.isnull().sum()

CANDIDATE_ID_x                                     154
APPLICATION_ID                                       0
JOB_REF_ID                                         154
JOB_TITLE                                          154
DEPARTMENT                                         154
POSITION_CATEGORY                                  154
POSITION                                           154
REGION                                            1610
USI_DIVERSITY_QUESTION_RACE                       1113
USI_DIVERSITY_QUESTION_GENDER                     1149
USI_UNCOMMON_AFFILIATION                           995
USI_GPA                                           3025
USI_TEACHER_CERT                                  3769
USI_TEACHING_EXPERIENCE                           3550
USI_HEARD_ABOUT_UNCOMMON                          1256
USI_OTHER_AFFILIATION                             1398
CANDIDATE_ID_y                                       0
Application Creation Date                            0
Job Title                                            0
Position                                           154
Position Category                                  154
Region                                            1610
Grade Level                                       2773
HO Team                                           3202
Application Status                                   0
Application Transfer Date                         4623
Application Status Before Rejection                507
Application Rejection Date                         507
Rejection Reason                                  1180
Application Status Before Withdrawal              4266
Application Withdrawal Date                       4266
Withdrawal Reason                                 4267
Application field: Secondary Withdrawal Reason    4658
[Unknown]                                            0
Time In Application State: Lead                      0
Time In Application State: New                       0
Time In Application State: In-Review                 0
Time In Application State: Interview                 0
Time In Application State: Offered                   0
Source                                               0
Application Creation Month                           0
num_applications                                     0
HIRED                                                0
INTERVIEW/Interview 1                                0
INTERVIEW/ON Hold: Pre-Interview                     0
INTERVIEW/On Hold: Pre Interview                     0
INTERVIEW/On Hold: Pre-interview                     0
INTERVIEW/Ready for Mgr Review                       0
IN_REVIEW/Application Review                         0
IN_REVIEW/ON HOLD: PRE-SCREEN                        0
IN_REVIEW/On Hold: Pre Screen                        0
REJECTED                                             0
TRANSFERRED                                          0
WITHDRAWN                                            0
Time In Application Process                          0
dtype: int64

### Number of applications per Application Status

In [996]:
data_april['Application Status'].unique()

array(['HIRED', 'REJECTED', 'WITHDRAWN', 'TRANSFERRED',
       'IN_REVIEW/ON HOLD: PRE-SCREEN', 'INTERVIEW/Ready for Mgr Review',
       'INTERVIEW/Interview 1', 'INTERVIEW/ON Hold: Pre-Interview',
       'IN_REVIEW/Application Review', 'INTERVIEW/On Hold: Pre Interview',
       'IN_REVIEW/On Hold: Pre Screen',
       'INTERVIEW/On Hold: Pre-interview'], dtype=object)

In [997]:
d = data_april['Application Status'].unique()
all_states = {}
len_all_states = {}
for state in d:
    all_states[state] = data_april[data_april['Application Status'] == state]
    len_all_states[state] = len(data_april[data_april['Application Status'] == state])

len_all_states

{'HIRED': 62,
 'REJECTED': 4151,
 'WITHDRAWN': 392,
 'TRANSFERRED': 35,
 'IN_REVIEW/ON HOLD: PRE-SCREEN': 9,
 'INTERVIEW/Ready for Mgr Review': 1,
 'INTERVIEW/Interview 1': 2,
 'INTERVIEW/ON Hold: Pre-Interview': 1,
 'IN_REVIEW/Application Review': 1,
 'INTERVIEW/On Hold: Pre Interview': 2,
 'IN_REVIEW/On Hold: Pre Screen': 1,
 'INTERVIEW/On Hold: Pre-interview': 1}

### Withdrawal
Application Status Before Withdrawal              
Application Withdrawal Date                       
Withdrawal Reason

In [1027]:
# Withdrawal
data_april[data_april['Application Status'] == 'WITHDRAWN'].head(3)

,CANDIDATE_ID_x,APPLICATION_ID,JOB_REF_ID,JOB_TITLE,DEPARTMENT,POSITION_CATEGORY,POSITION,REGION,USI_DIVERSITY_QUESTION_RACE,USI_DIVERSITY_QUESTION_GENDER,...,INTERVIEW/On Hold: Pre Interview,INTERVIEW/On Hold: Pre-interview,INTERVIEW/Ready for Mgr Review,IN_REVIEW/Application Review,IN_REVIEW/ON HOLD: PRE-SCREEN,IN_REVIEW/On Hold: Pre Screen,REJECTED,TRANSFERRED,WITHDRAWN,Time In Application Process
440,29b0cb9f-c216-4f9e-a2a6-8166f776b637,e8c895d0-9bbf-4514-97d3-6d52ecdc8594,REF167D,Middle School ELA Teacher (Immediate Start),Teaching and Instruction,Core Teacher,MS ELA Teacher,Newark,NaN,NaN,...,0,0,0,0,0,0,0,0,1,2.0
447,aeac7d7b-4965-4666-84fc-b04810d1c5f8,aeac7d7b-4965-4666-84fc-b04810d1c5f8,REF77R,Office Manager (Immediate Start),School-Based Operations,School Based Operations,Office Manager,Newark,Hispanic or Latinx,Female,...,0,0,0,0,0,0,0,0,1,1.0
565,4b2e53bc-63a7-4c1d-aa48-f9c253ef8d56,4b2e53bc-63a7-4c1d-aa48-f9c253ef8d56,REF107Q,Elementary Teacher (Immediate Start SY 18-19),Teaching and Instruction,Core Teacher,Elementary School Teacher,Newark,Hispanic or Latinx,Female,...,0,0,0,0,0,0,0,0,1,1.0

In [1028]:
# Withdrawal reason
data_april[data_april['Application Status'] == 'WITHDRAWN']['Withdrawal Reason'].unique()

array(['Not responsive to recruiter', 'Unknown', 'Cultural fit',
       'Time in process', 'Compensation', 'Took another job',
       'Personal reasons', 'Not interested in the first place',
       'Not a position fit', 'Took another job in education', 'Commute',
       'Did not show up to interview', 'Will stay in current company',
       'Graduate school', 'Not willing to relocate',
       'Never received transcript/GPA', nan], dtype=object)

In [1041]:
withdrawn_df = data_april[data_april['Application Status'] == 'WITHDRAWN']
d = withdrawn_df['Withdrawal Reason'].unique()
all_withdrawn = {}
len_all_withdrawn = {}
for state in d:
    all_withdrawn[state] = withdrawn_df[withdrawn_df['Withdrawal Reason'] == state]
    len_all_withdrawn[state] = len(withdrawn_df[withdrawn_df['Withdrawal Reason'] == state])

len_all_withdrawn

{'Not responsive to recruiter': 252,
 'Unknown': 22,
 'Cultural fit': 3,
 'Time in process': 5,
 'Compensation': 27,
 'Took another job': 28,
 'Personal reasons': 11,
 'Not interested in the first place': 12,
 'Not a position fit': 9,
 'Took another job in education': 7,
 'Commute': 4,
 'Did not show up to interview': 6,
 'Will stay in current company': 1,
 'Graduate school': 2,
 'Not willing to relocate': 1,
 'Never received transcript/GPA': 1,
 nan: 0}

### Rejection
Application Status Before Rejection               
Application Rejection Date                       
Rejection Reason

In [1042]:
# Rejection reason
data_april[data_april['Application Status'] == 'REJECTED']['Rejection Reason'].unique()

array(['Did not meet screening requirements', 'Position filled', nan,
       'Did not meet desired qualifications',
       'Did not meet minimum qualifications',
       'More qualified candidate selected', 'Overqualified for Role',
       'Moved to/In process for a different role', 'Other',
       'Reference check concerns', 'Incomplete application',
       'Unresponsive', 'Did not fit company culture',
       'No show for interview',
       'Availability does not align with position start date',
       'Ineligible to work in location', 'Does not meet GPA requirements'],
      dtype=object)

In [1043]:
rejection_df = data_april[data_april['Application Status'] == 'REJECTED']
d = rejection_df['Rejection Reason'].unique()
all_rejection = {}
len_all_rejection = {}
for state in d:
    all_rejection[state] = rejection_df[rejection_df['Rejection Reason'] == state]
    len_all_rejection[state] = len(rejection_df[rejection_df['Rejection Reason'] == state])

len_all_rejection

{'Did not meet screening requirements': 2284,
 'Position filled': 32,
 nan: 0,
 'Did not meet desired qualifications': 288,
 'Did not meet minimum qualifications': 403,
 'More qualified candidate selected': 72,
 'Overqualified for Role': 142,
 'Moved to/In process for a different role': 192,
 'Other': 26,
 'Reference check concerns': 3,
 'Incomplete application': 4,
 'Unresponsive': 4,
 'Did not fit company culture': 23,
 'No show for interview': 1,
 'Availability does not align with position start date': 1,
 'Ineligible to work in location': 1,
 'Does not meet GPA requirements': 2}

### Data per position category

In [998]:
data_april['POSITION_CATEGORY'].unique()

array(['Student Support', 'Core Teacher', 'School Based Operations',
       'Operational Leadership', 'College Completion',
       'Apprentice Teacher', 'Home Office', 'General Teacher',
       'Instructional Leadership', 'Regional Support Staff',
       'Specials Teacher', 'Summer Teaching Fellows', nan], dtype=object)

#### Applications per position category

In [999]:
# New column for num_applications
data_april['num_applications']= 1

data_april.head(3)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,CANDIDATE_ID_x,APPLICATION_ID,JOB_REF_ID,JOB_TITLE,DEPARTMENT,POSITION_CATEGORY,POSITION,REGION,USI_DIVERSITY_QUESTION_RACE,USI_DIVERSITY_QUESTION_GENDER,...,Application field: Secondary Withdrawal Reason,[Unknown],Time In Application State: Lead,Time In Application State: New,Time In Application State: In-Review,Time In Application State: Interview,Time In Application State: Offered,Source,Application Creation Month,num_applications
0,e9263572-f945-4e2e-bf66-6ae0c25c56f5,f72b1b7e-f35f-4f2a-aa79-cb29c8ff73e6,REF13L,Dean of Students,Student Services,Student Support,Dean Of Students,Troy,NaN,NaN,...,NaN,False,1.0,1.0,NaN,13.0,NaN,Katie Yezzi,4,1
4,6233f272-d866-4927-b901-8bab73213a29,6233f272-d866-4927-b901-8bab73213a29,REF52A,Middle School ELA Teacher (Immediate Start),Teaching and Instruction,Core Teacher,MS ELA Teacher,Boston,White,Female,...,NaN,False,NaN,3.0,2.0,11.0,13.0,RoxburyPrep Jobs,4,1
22,39f00a50-7902-4a7c-9c6c-ba6228e8c3d5,538d93b0-4f0d-4266-a0db-77c26c4d5f33,REF56L,Middle School History Teacher (Immediate Start),Teaching and Instruction,Core Teacher,MS History Teacher,Rochester,NaN,NaN,...,NaN,False,1.0,1.0,NaN,NaN,NaN,Default Career Page,4,1

In [1000]:
# Dummy variables for Application Status column (and add to dataframe)
data_april = pd.concat([data_april, pd.get_dummies(data_april['Application Status'])], axis=1)

data_april.head(3)

,CANDIDATE_ID_x,APPLICATION_ID,JOB_REF_ID,JOB_TITLE,DEPARTMENT,POSITION_CATEGORY,POSITION,REGION,USI_DIVERSITY_QUESTION_RACE,USI_DIVERSITY_QUESTION_GENDER,...,INTERVIEW/ON Hold: Pre-Interview,INTERVIEW/On Hold: Pre Interview,INTERVIEW/On Hold: Pre-interview,INTERVIEW/Ready for Mgr Review,IN_REVIEW/Application Review,IN_REVIEW/ON HOLD: PRE-SCREEN,IN_REVIEW/On Hold: Pre Screen,REJECTED,TRANSFERRED,WITHDRAWN
0,e9263572-f945-4e2e-bf66-6ae0c25c56f5,f72b1b7e-f35f-4f2a-aa79-cb29c8ff73e6,REF13L,Dean of Students,Student Services,Student Support,Dean Of Students,Troy,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
4,6233f272-d866-4927-b901-8bab73213a29,6233f272-d866-4927-b901-8bab73213a29,REF52A,Middle School ELA Teacher (Immediate Start),Teaching and Instruction,Core Teacher,MS ELA Teacher,Boston,White,Female,...,0,0,0,0,0,0,0,0,0,0
22,39f00a50-7902-4a7c-9c6c-ba6228e8c3d5,538d93b0-4f0d-4266-a0db-77c26c4d5f33,REF56L,Middle School History Teacher (Immediate Start),Teaching and Instruction,Core Teacher,MS History Teacher,Rochester,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0

In [1001]:
# See how many applications and application status per position category
sum_poscat = data_april.groupby(['POSITION_CATEGORY']).sum()

sum_poscat

,[Unknown],Time In Application State: Lead,Time In Application State: New,Time In Application State: In-Review,Time In Application State: Interview,Time In Application State: Offered,Application Creation Month,num_applications,HIRED,INTERVIEW/Interview 1,INTERVIEW/ON Hold: Pre-Interview,INTERVIEW/On Hold: Pre Interview,INTERVIEW/On Hold: Pre-interview,INTERVIEW/Ready for Mgr Review,IN_REVIEW/Application Review,IN_REVIEW/ON HOLD: PRE-SCREEN,IN_REVIEW/On Hold: Pre Screen,REJECTED,TRANSFERRED,WITHDRAWN
POSITION_CATEGORY,,,,,,,,,,,,,,,,,,,,
Apprentice Teacher,0.0,67.0,618.0,549.0,536.0,114.0,656,164,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,127.0,12.0,17.0
College Completion,0.0,115.0,555.0,374.0,561.0,60.0,956,239,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,227.0,1.0,5.0
Core Teacher,0.0,783.0,1482.0,5443.0,2544.0,296.0,2308,577,27.0,0.0,0.0,1.0,0.0,1.0,0.0,3.0,0.0,382.0,4.0,159.0
General Teacher,0.0,533.0,1215.0,2389.0,851.0,44.0,1432,358,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,287.0,11.0,60.0
Home Office,3.0,1608.0,2494.0,3919.0,1313.0,36.0,5824,1456,4.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1365.0,1.0,83.0
Instructional Leadership,0.0,189.0,340.0,246.0,110.0,6.0,572,143,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,138.0,1.0,4.0
Operational Leadership,0.0,2293.0,668.0,686.0,331.0,100.0,2696,674,7.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,656.0,1.0,9.0
Regional Support Staff,0.0,0.0,263.0,70.0,0.0,0.0,204,51,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,51.0,0.0,0.0
School Based Operations,0.0,558.0,1006.0,1883.0,540.0,32.0,1688,422,4.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0,0.0,373.0,0.0,41.0
Specials Teacher,0.0,132.0,200.0,409.0,76.0,0.0,224,56,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,52.0,0.0,4.0
Student Support,0.0,584.0,1662.0,2235.0,965.0,24.0,1424,356,6.0,0.0,0.0,1.0,0.0,0.0,0.0,3.0,1.0,334.0,1.0,10.0
Summer Teaching Fellows,0.0,8.0,8.0,0.0,0.0,0.0,32,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0

In [1002]:
# drop columns not needed
sum_poscat1 = sum_poscat.drop(['[Unknown]', 'Time In Application State: Lead', 'Time In Application State: New',
                              'Time In Application State: In-Review', 'Time In Application State: Interview',
                              'Time In Application State: Offered', 'Application Creation Month'], axis=1)

sum_poscat1

,num_applications,HIRED,INTERVIEW/Interview 1,INTERVIEW/ON Hold: Pre-Interview,INTERVIEW/On Hold: Pre Interview,INTERVIEW/On Hold: Pre-interview,INTERVIEW/Ready for Mgr Review,IN_REVIEW/Application Review,IN_REVIEW/ON HOLD: PRE-SCREEN,IN_REVIEW/On Hold: Pre Screen,REJECTED,TRANSFERRED,WITHDRAWN
POSITION_CATEGORY,,,,,,,,,,,,,
Apprentice Teacher,164,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,127.0,12.0,17.0
College Completion,239,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,227.0,1.0,5.0
Core Teacher,577,27.0,0.0,0.0,1.0,0.0,1.0,0.0,3.0,0.0,382.0,4.0,159.0
General Teacher,358,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,287.0,11.0,60.0
Home Office,1456,4.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1365.0,1.0,83.0
Instructional Leadership,143,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,138.0,1.0,4.0
Operational Leadership,674,7.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,656.0,1.0,9.0
Regional Support Staff,51,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,51.0,0.0,0.0
School Based Operations,422,4.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0,0.0,373.0,0.0,41.0
Specials Teacher,56,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,52.0,0.0,4.0
Student Support,356,6.0,0.0,0.0,1.0,0.0,0.0,0.0,3.0,1.0,334.0,1.0,10.0
Summer Teaching Fellows,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0

In [1003]:
# See average time in different application states per position category
avg_timein = data_april.groupby(['POSITION_CATEGORY']).mean()

avg_timein

,[Unknown],Time In Application State: Lead,Time In Application State: New,Time In Application State: In-Review,Time In Application State: Interview,Time In Application State: Offered,Application Creation Month,num_applications,HIRED,INTERVIEW/Interview 1,INTERVIEW/ON Hold: Pre-Interview,INTERVIEW/On Hold: Pre Interview,INTERVIEW/On Hold: Pre-interview,INTERVIEW/Ready for Mgr Review,IN_REVIEW/Application Review,IN_REVIEW/ON HOLD: PRE-SCREEN,IN_REVIEW/On Hold: Pre Screen,REJECTED,TRANSFERRED,WITHDRAWN
POSITION_CATEGORY,,,,,,,,,,,,,,,,,,,,
Apprentice Teacher,0.00000,2.233333,4.352113,5.278846,26.800000,16.285714,4,1,0.048780,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.774390,0.073171,0.103659
College Completion,0.00000,19.166667,2.341772,1.640351,23.375000,8.571429,4,1,0.025105,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.949791,0.004184,0.020921
Core Teacher,0.00000,4.350000,2.855491,12.231461,22.714286,16.444444,4,1,0.046794,0.000000,0.00000,0.001733,0.000000,0.001733,0.000000,0.005199,0.000000,0.662045,0.006932,0.275563
General Teacher,0.00000,9.033898,3.944805,8.881041,24.314286,7.333333,4,1,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.801676,0.030726,0.167598
Home Office,0.00206,7.514019,2.092282,3.864892,29.840909,9.000000,4,1,0.002747,0.001374,0.00000,0.000000,0.000000,0.000000,0.000687,0.000000,0.000000,0.937500,0.000687,0.057005
Instructional Leadership,0.00000,11.117647,2.575758,1.906977,27.500000,6.000000,4,1,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.965035,0.006993,0.027972
Operational Leadership,0.00000,7.643333,1.699746,1.795812,16.550000,14.285714,4,1,0.010386,0.000000,0.00000,0.000000,0.001484,0.000000,0.000000,0.000000,0.000000,0.973294,0.001484,0.013353
Regional Support Staff,0.00000,NaN,5.156863,1.489362,NaN,NaN,4,1,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
School Based Operations,0.00000,19.241379,2.668435,5.706061,22.500000,10.666667,4,1,0.009479,0.000000,0.00237,0.000000,0.000000,0.000000,0.000000,0.007109,0.000000,0.883886,0.000000,0.097156
Specials Teacher,0.00000,10.153846,4.347826,9.975610,25.333333,NaN,4,1,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.928571,0.000000,0.071429
Student Support,0.00000,12.977778,5.082569,8.097826,35.740741,8.000000,4,1,0.016854,0.000000,0.00000,0.002809,0.000000,0.000000,0.000000,0.008427,0.002809,0.938202,0.002809,0.028090
Summer Teaching Fellows,0.00000,1.000000,1.000000,NaN,NaN,NaN,4,1,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000

In [1004]:
# drop columns not needed
avg_timein1 = avg_timein.drop(['[Unknown]', 'num_applications', 'INTERVIEW/Interview 1',
                              'HIRED', 'INTERVIEW/ON Hold: Pre-Interview', 'INTERVIEW/On Hold: Pre Interview',
                              'INTERVIEW/On Hold: Pre-interview', 'INTERVIEW/Ready for Mgr Review',
                              'IN_REVIEW/Application Review', 'IN_REVIEW/ON HOLD: PRE-SCREEN',
                              'IN_REVIEW/On Hold: Pre Screen', 'REJECTED', 'TRANSFERRED', 'WITHDRAWN',
                              'Application Creation Month'], axis=1)

avg_timein1

,Time In Application State: Lead,Time In Application State: New,Time In Application State: In-Review,Time In Application State: Interview,Time In Application State: Offered
POSITION_CATEGORY,,,,,
Apprentice Teacher,2.233333,4.352113,5.278846,26.800000,16.285714
College Completion,19.166667,2.341772,1.640351,23.375000,8.571429
Core Teacher,4.350000,2.855491,12.231461,22.714286,16.444444
General Teacher,9.033898,3.944805,8.881041,24.314286,7.333333
Home Office,7.514019,2.092282,3.864892,29.840909,9.000000
Instructional Leadership,11.117647,2.575758,1.906977,27.500000,6.000000
Operational Leadership,7.643333,1.699746,1.795812,16.550000,14.285714
Regional Support Staff,NaN,5.156863,1.489362,NaN,NaN
School Based Operations,19.241379,2.668435,5.706061,22.500000,10.666667
Specials Teacher,10.153846,4.347826,9.975610,25.333333,NaN
Student Support,12.977778,5.082569,8.097826,35.740741,8.000000
Summer Teaching Fellows,1.000000,1.000000,NaN,NaN,NaN

### Applications per Region

In [1005]:
# See how many applications and application status per Region
data_april_region = data_april.groupby(['Region']).sum()

data_april_region

,[Unknown],Time In Application State: Lead,Time In Application State: New,Time In Application State: In-Review,Time In Application State: Interview,Time In Application State: Offered,Application Creation Month,num_applications,HIRED,INTERVIEW/Interview 1,INTERVIEW/ON Hold: Pre-Interview,INTERVIEW/On Hold: Pre Interview,INTERVIEW/On Hold: Pre-interview,INTERVIEW/Ready for Mgr Review,IN_REVIEW/Application Review,IN_REVIEW/ON HOLD: PRE-SCREEN,IN_REVIEW/On Hold: Pre Screen,REJECTED,TRANSFERRED,WITHDRAWN
Region,,,,,,,,,,,,,,,,,,,,
Boston,False,1073.0,1824.0,2316.0,643.0,65.0,2200,550,6.0,0.0,0.0,1.0,0.0,0.0,0.0,7.0,0.0,511.0,5.0,20.0
Camden,False,1324.0,1069.0,3499.0,1159.0,125.0,2244,561,7.0,0.0,1.0,0.0,1.0,0.0,0.0,2.0,0.0,460.0,1.0,89.0
Newark,False,1923.0,2561.0,5399.0,3138.0,222.0,5068,1267,23.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1088.0,12.0,141.0
Rochester,False,846.0,1548.0,1684.0,1028.0,179.0,1516,379,16.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,320.0,13.0,30.0
Troy,False,96.0,1015.0,1386.0,546.0,85.0,1164,291,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,256.0,0.0,29.0

In [1048]:
data_april[data_april['POSITION_CATEGORY'] == 'Home Office']

,CANDIDATE_ID_x,APPLICATION_ID,JOB_REF_ID,JOB_TITLE,DEPARTMENT,POSITION_CATEGORY,POSITION,REGION,USI_DIVERSITY_QUESTION_RACE,USI_DIVERSITY_QUESTION_GENDER,...,INTERVIEW/On Hold: Pre Interview,INTERVIEW/On Hold: Pre-interview,INTERVIEW/Ready for Mgr Review,IN_REVIEW/Application Review,IN_REVIEW/ON HOLD: PRE-SCREEN,IN_REVIEW/On Hold: Pre Screen,REJECTED,TRANSFERRED,WITHDRAWN,Time In Application Process
142,3c39906b-8915-4ed1-8134-3bfe74b41590,3c39906b-8915-4ed1-8134-3bfe74b41590,REF256W,Executive Assistant to the CFO,Home Office,Home Office,Associate Director,NaN,Hispanic or Latinx,Female,...,0,0,0,0,0,0,0,0,0,1.0
167,3f5df826-c4c8-4689-a530-0710225ace98,3f5df826-c4c8-4689-a530-0710225ace98,REF265Z,Senior Associate Director of College Completion,Home Office,Home Office,Senior Associate Director,NaN,Black or African American,Female,...,0,0,0,0,0,0,0,0,0,1.0
171,69e207b0-a7bf-4012-9f97-ea9fda745393,69e207b0-a7bf-4012-9f97-ea9fda745393,REF268R,Operations Coordinator,Home Office,Home Office,Coordinator,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,2.0
198,db0f725f-a807-4b78-8168-b27fe82b3876,db0f725f-a807-4b78-8168-b27fe82b3876,REF241V,Associate/Senior Associate Director of Literac...,Home Office,Home Office,Associate Director,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,1.0
439,6938e66f-92d9-48c0-a10c-27b103b36834,6938e66f-92d9-48c0-a10c-27b103b36834,REF229N,"Senior Associate Director of IT, Support (Tier...",Home Office,Home Office,Senior Associate Director,NaN,"Asian,I prefer not to say",Male,...,0,0,0,0,0,0,1,0,0,6.0
556,03cf63b8-8edd-4760-a6ef-1d31ebc2716d,03cf63b8-8edd-4760-a6ef-1d31ebc2716d,REF268R,Operations Coordinator,Home Office,Home Office,Coordinator,NaN,Black or African American,Male,...,0,0,0,0,0,0,1,0,0,2.0
568,4897eeda-95b5-4717-a235-00fa3f6d6e0d,4897eeda-95b5-4717-a235-00fa3f6d6e0d,REF255C,Business Analyst,Home Office,Home Office,Associate Director,NaN,Asian,Male,...,0,0,0,0,0,0,1,0,0,1.0
630,2b27453f-adc4-412e-877e-c5e4d6cd9c19,af93285b-510b-48cb-bce7-a43c820612a7,REF268R,Operations Coordinator,Home Office,Home Office,Coordinator,NaN,Asian,Female,...,0,0,0,0,0,0,1,0,0,2.0
641,86a5bec3-418d-477c-941f-1ce7d3792073,86a5bec3-418d-477c-941f-1ce7d3792073,REF146W,General Maintenance Worker,Home Office,Home Office,General Maintenance Worker,NaN,NaN,Female,...,0,0,0,0,0,0,1,0,0,2.0
661,40b1ef4e-6708-4695-8eb2-2d8376d0714f,40b1ef4e-6708-4695-8eb2-2d8376d0714f,REF154K,Grant Writer,Home Office,Home Office,Associate Director,NaN,NaN,NaN,...,0,0,0,0,0,0,1,0,0,1.0
683,743a523d-5627-46af-8de6-7002816a0f4e,743a523d-5627-46af-8de6-7002816a0f4e,REF255C,Business Analyst,Home Office,Home Office,Associate Director,NaN,NaN,Male,...,0,0,0,0,0,0,1,0,0,1.0
732,cdadc54e-564e-4917-9fee-e1ecaed0fe99,cdadc54e-564e-4917-9fee-e1ecaed0fe99,REF243X,Senior Associate Director of School Management,Home Office,Home Office,Senior Associate Director,NaN,Asian,Female,...,0,0,0,0,0,0,1,0,0,1.0
739,57c151a8-de3b-4442-a8ed-e4a4914c2f66,57c151a8-de3b-4442-a8ed-e4a4914c2f66,REF229N,"Senior Associate Director of IT, Support (Tier...",Home Office,Home Office,Senior Associate Director,NaN,I prefer not to say,Male,...,0,0,0,0,0,0,1,0,0,2.0
789,d5a44fdb-31d1-4f7e-bcb8-9606f16319c4,d5a44fdb-31d1-4f7e-bcb8-9606f16319c4,REF255C,Business Analyst,Home Office,Home Office,Associate Director,NaN,Asian,Male,...,0,0,0,0,0,0,1,0,0,2.0
790,36b613aa-be85-49fa-8c73-2c3191d15343,36b613aa-be85-49fa-8c73-2c3191d15343,REF255C,Business Analyst,Home Office,Home Office,Associate Director,NaN,White,Male,...,0,0,0,0,0,0,0,0,1,1.0
793,9a9b635c-b101-4d62-907f-3edd22f43eab,9a9b635c-b101-4d62-907f-3edd22f43eab,REF268R,Operations Coordinator,Home Office,Home Office,Coordinator,NaN,Asian,Female,...,0,0,0,0,0,0,1,0,0,1.0
830,efc3e080-5e3d-469b-9e4d-ac75af321767,7934e43c-0aa7-48e9-9303-73569fef04da,REF268R,Operations Coordinator,Home Office,Home Office,Coordinator,NaN,Multi-racial,Female,...,0,0,0,0,0,0,1,0,0,3.0
834,0de0c5f1-c5e5-4061-b5de-2cddab71e4b5,73af54d6-a184-4005-bf9d-b10eebf2c08a,REF265Z,Senior Associate Director of College Completion,Home Office,Home Office,Senior Associate Director,NaN,NaN,NaN,...,0,0,0,0,0,0,1,0,0,2.0
836,c3223873-821d-4149-b3d5-d156335a0688,c3223873-821d-4149-b3d5-d156335a0688,REF256W,Executive Assistant to the CFO,Home Office,Home Office,Associate Director,NaN,Hispanic or Latinx,Female,...,0,0,0,0,0,0,1,0,0,1.0
845,f3f4d9e8-8d2f-4306-a8e8-580b72ec1fd3,8720fcd8-8755-49de-8d50-671166ac71df,REF147L,Special Assistant to the CEO,Home Office,Home Office,Associate Director,NaN,Black or African American,Female,...,0,0,0,0,0,0,1,0,0,1.0
862,ceb1d55e-c081-4ed1-883c-d2c767f2ded8,ceb1d55e-c081-4ed1-883c-d2c767f2ded8,REF255C,Business Analyst,Home Office,Home Office,Associate Director,NaN,Asian,Female,...,0,0,0,0,0,0,1,0,0,1.0
882,55dcaafc-6e01-44dd-ae23-6244763b45a4,fb27d62e-9843-4482-8add-d2a749b624e9,REF154K,Grant Writer,Home Office,Home Office,Associate Director,NaN,Asian,Female,...,0,0,0,0,0,0,1,0,0,1.0
893,53c3558c-b420-4518-8232-67d5b56222eb,53c3558c-b420-4518-8232-67d5b56222eb,REF265Z,Senior Associate Director of College Completion,Home Office,Home Office,Senior Associate Director,NaN,Asian,Male,...,0,0,0,0,0,0,1,0,0,1.0
899,6ab80f40-7d5e-4040-8adc-61889b0cce16,6ab80f40-7d5e-4040-8adc-61889b0cce16,REF257D,Director of Development,Home Office,Home Office,Director,NaN,NaN,NaN,...,0,0,0,0,0,0,1,0,0,9.0
901,fdcaeac5-7526-4622-a3da-7a78cff38396,fdcaeac5-7526-4622-a3da-7a78cff38396,REF283K,Director of Strategy & Operations,Home Office,Home Office,Senior Associate Director,NaN,Black or African American,Male,...,0,0,0,0,0,0,1,0,0,1.0
913,b7185162-b25c-4ec9-9753-ec0345b81515,b7185162-b25c-4ec9-9753-ec0345b81515,REF256W,Executive Assistant to the CFO,Home Office,Home Office,Associate Director,NaN,Hispanic or Latinx,Female,...,0,0,0,0,0,0,1,0,0,1.0
925,4d3a9411-3561-4d70-8217-89ccd8a5609b,4d3a9411-3561-4d70-8217-89ccd8a5609b,REF236M,Student Recruitment Coordinator (Immediate Start),Home Office,Home Office,Coordinator,NaN,Black or African American,Female,...,0,0,0,0,0,0,1,0,0,0.0
966,ad5b4425-5f47-4bc1-9daf-7edb28f63759,ad5b4425-5f47-4bc1-9daf-7edb28f63759,REF268R,Operations Coordinator,Home Office,Home Office,Coordinator,NaN,Black or African American,Female,...,0,0,0,0,0,0,1,0,0,1.0
982,2b1860bc-2ce6-40e8-8b26-2903faa57365,2b1860bc-2ce6-40e8-8b26-2903faa57365,REF229N,"Senior Associate Director of IT, Support (Tier...",Home Office,Home Office,Senior Associate Director,NaN,White,Male,...,0,0,0,0,0,0,1,0,0,2.0
1052,fa3b715b-1917-4b17-b508-5d764cc29525,fa3b715b-1917-4b17-b508-5d764cc29525,REF242G,Senior Associate Director of Operations,Home Office,Home Office,Senior Associate Director,NaN,White,Male,...,0,0,0,0,0,0,1,0,0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31909,599617f3-0a7c-4e1c-b084-0f3031c0fe18,599617f3-0a7c-4e1c-b084-0f3031c0fe18,REF255C,Business Analyst,Home Office,Home Office,Associate Director,NaN,NaN,Female,...,0,0,0,0,0,0,1,0,0,1.0
31911,fcef8a44-83ce-4e39-9fee-3521f4a2e045,fcef8a44-83ce-4e39-9fee-3521f4a2e045,REF243X,Senior Associate Director of School Management,Home Office,Home Office,Senior Associate Director,NaN,White,Female,...,0,0,0,0,0,0,1,0,0,1.0
31913,7091c064-d8d7-4799-8c49-bea4e8977fd3,7091c064-d8d7-4799-8c49-bea4e8977fd3,REF255C,Business Analyst,Home Office,Home Office,Associate Director,NaN,I prefer not to say,I prefer not to say,...,0,0,0,0,0,0,1,0,0,1.0
31937,70e8277b-7e3c-46a9-8e0f-3468c0152df4,70e8277b-7e3c-46a9-8e0f-3468c0152df4,REF255C,Business Analyst,Home Office,Home Office,Associate Director,NaN,Asian,Female,...,0,0,0,0,0,0,1,0,0,1.0
31939,651be3d1-5469-46fb-b9f8-7dc2e62f8ca3,651be3d1-5469-46fb-b9f8-7dc2e62f8ca3,REF265Z,Senior Associate Director of College Completion,Home Office,Home Office,Senior Associate Director,NaN,Black or African American,Male,...,0,0,0,0,0,0,1,0,0,1.0
31948,e3e67638-da7b-493b-ae82-a1425364be33,e3e67638-da7b-493b-ae82-a1425364be33,REF236M,Student Recruitment Coordinator (Immediate Start),Home Office,Home Office,Coordinator,NaN,Black or African American,Female,...,0,0,0,0,0,0,1,0,0,1.0
32003,69eba95f-6544-4f2f-a930-b40403efa341,69eba95f-6544-4f2f-a930-b40403efa341,REF255C,Business Analyst,Home Office,Home Office,Associate Director,NaN,White,Male,...,0,0,0,0,0,0,1,0,0,1.0
32021,277731f8-8ea8-40d5-b1f9-50e7ed528b2e,277731f8-8ea8-40d5-b1f9-50e7ed528b2e,REF268R,Operations Coordinator,Home Office,Home Office,Coordinator,NaN,White,Female,...,0,0,0,0,0,0,1,0,0,1.0
32093,8005bfe7-6962-4f20-bff3-c2169a7688ad,8005bfe7-6962-4f20-bff3-c2169a7688ad,REF268R,Operations Coordinator,Home Office,Home Office,Coordinator,NaN,White,Male,...,0,0,0,0,0,0,1,0,0,1.0
32107,365a454c-20c2-4204-bb8e-9ac0b3abb044,365a454c-20c2-4204-bb8e-9ac0b3abb044,REF255C,Business Analyst,Home Office,Home Office,Associate Director,NaN,Asian,Male,...,0,0,0,0,0,0,1,0,0,1.0
32110,8ac40691-b5bc-44f8-bfa5-1a6b2862df27,8ac40691-b5bc-44f8-bfa5-1a6b2862df27,REF242G,Senior Associate Director of Operations,Home Office,Home Office,Senior Associate Director,NaN,NaN,NaN,...,0,0,0,0,0,0,1,0,0,4.0
32130,e4b4148a-13f2-453d-885b-38d5005344fc,e4b4148a-13f2-453d-885b-38d5005344fc,REF268R,Operations Coordinator,Home Office,Home Office,Coordinator,NaN,White,Queer,...,0,0,0,0,0,0,1,0,0,3.0
32144,2fa7b761-0040-45c7-b259-2e1cfef98675,2fa7b761-0040-45c7-b259-2e1cfef98675,REF255C,Business Analyst,Home Office,Home Office,Associate Director,NaN,Asian,Female,...,0,0,0,0,0,0,1,0,0,1.0
32153,44ca8502-f277-4a42-a6a1-ef5f099f926c,44ca8502-f277-4a42-a6a1-ef5f099f926c,REF265Z,Senior Associate Director of College Completion,Home Office,Home Office,Senior Associate Director,NaN,NaN,NaN,...,0,0,0,0,0,0,1,0,0,2.0
32180,a221349f-cf9e-495e-b4f1-7b7d8768f6df,a221349f-cf9e-495e-b4f1-7b7d8768f6df,REF255C,Business Analyst,Home Office,Home Office,Associate Director,NaN,Asian,Female,...,0,0,0,0,0,0,1,0,0,1.0
32199,1848e136-67a8-4132-8976-997aac5c4c5b,1848e136-67a8-4132-8976-997aac5c4c5b,REF255C,Business Analyst,Home Office,Home Office,Associate Director,NaN,White,Male,...,0,0,0,0,0,0,1,0,0,1.0
32226,13d33b1c-cc2c-4acb-8bde-e7daf9582c27,13d33b1c-cc2c-4acb-8bde-e7daf9582c27,REF228U,"Senior Associate Director of IT, Support (SIS ...",Home Office,Home Office,Senior Associate Director,NaN,White,Male,...,0,0,0,0,0,0,0,0,1,10.0
32252,8e0a9a70-aea8-4bb8-822e-a8b19b48f357,8e0a9a70-aea8-4bb8-822e-a8b19b48f357,REF242G,Senior Associate Director of Operations,Home Office,Home Office,Senior Associate Director,NaN,NaN,NaN,...,0,0,0,0,0,0,1,0,0,1.0
32254,887ab0cd-01bd-41e0-bd69-6a60ca0f5e71,fb4be4e5-f22b-42aa-b05e-2535ff947c01,REF266R,Technical Program Manager (Innovation Fellow a...,Home Office,Home Office,Senior Associate Director,NaN,Black or African American,Female,...,0,0,0,0,0,0,1,0,0,3.0
32261,53370070-574e-45cf-9c4d-d336a64c0eea,53370070-574e-45cf-9c4d-d336a64c0eea,REF255C,Business Analyst,Home Office,Home Office,Associate Director,NaN,White,Female,...,0,0,0,0,0,0,1,0,0,1.0
32262,784ba694-f974-45a2-9e59-cf85625426ef,784ba694-f974-45a2-9e59-cf85625426ef,REF268R,Operations Coordinator,Home Office,Home Office,Coordinator,NaN,NaN,NaN,...,0,0,0,0,0,0,1,0,0,23.0
32284,604db79b-68bd-4dc5-bb92-82738aa27870,604db79b-68bd-4dc5-bb92-82738aa27870,REF236M,Student Recruitment Coordinator (Immediate Start),Home Office,Home Office,Coordinator,NaN,Black or African American,Female,...,0,0,0,0,0,0,1,0,0,1.0
32319,75dffbe8-70fe-48cf-be6b-725078e6d77f,75dffbe8-70fe-48cf-be6b-725078e6d77f,REF255C,Business Analyst,Home Office,Home Office,Associate Director,NaN,Multi-racial,Female,...,0,0,0,0,0,0,1,0,0,1.0
32368,20c287df-77a8-4e07-9b49-a1a3f882e66c,20c287df-77a8-4e07-9b49-a1a3f882e66c,REF257D,Director of Development,Home Office,Home Office,Director,NaN,NaN,NaN,...,0,0,0,0,0,0,1,0,0,8.0
32389,75a1a058-2908-4168-863e-6a8bc4242bdc,30bd6fa0-746f-401d-9c17-d2147e3e5d60,REF283K,Director of Strategy & Operations,Home Office,Home Office,Senior Associate Director,NaN,White,Male,...,0,0,0,0,0,0,1,0,0,0.0
32390,fb58deb2-88bd-47d0-9395-fba5f932c1e4,953b51aa-a41c-462f-9d5a-5f3a9875447c,REF242G,Senior Associate Director of Operations,Home Office,Home Office,Senior Associate Director,NaN,Black or African American,Male,...,0,0,0,0,0,0,1,0,0,1.0
32398,1d1dd31d-ece5-4077-9de2-f4d5021d1c08,1d1dd31d-ece5-4077-9de2-f4d5021d1c08,REF199N,Professional Development Writer,Home Office,Home Office,Associate Director,NaN,White,Female,...,0,0,0,0,0,0,1,0,0,3.0
32403,1d0a7108-9883-481c-9dc7-35683d0880f5,1d0a7108-9883-481c-9dc7-35683d0880f5,REF257D,Director of Development,Home Office,Home Office,Director,NaN,NaN,NaN,...,0,0,0,0,0,0,1,0,0,9.0
32415,272b9952-734a-4a76-96a1-2f5f72b0f439,272b9952-734a-4a76-96a1-2f5f72b0f439,REF255C,Business Analyst,Home Office,Home Office,Associate Director,NaN,Asian,Male,...,0,0,0,0,0,0,1,0,0,1.0
32432,bb47b33d-08b1-4bc8-9f28-ebfefb68382b,bb47b33d-08b1-4bc8-9f28-ebfefb68382b,REF257D,Director of Development,Home Office,Home Office,Director,NaN,White,Male,...,0,0,0,0,0,0,1,0,0,1.0

In [ ]:
# 1456 has the position category Home Office
# They do not have a region

### Gendersplit

In [1006]:
data_april['USI_DIVERSITY_QUESTION_GENDER'].unique()

array([nan, 'Female', 'Male', 'I prefer not to say', 'Queer',
       'Transgender', 'I prefer not to say,Male', 'Gender Non-Conforming'],
      dtype=object)

In [1007]:
d = data_april['USI_DIVERSITY_QUESTION_GENDER'].unique()
all_gender = {}
len_all_gender = {}
for gender in d:
    all_gender[gender] = data_april[data_april['USI_DIVERSITY_QUESTION_GENDER'] == gender]
    len_all_gender[gender] = len(data_april[data_april['USI_DIVERSITY_QUESTION_GENDER'] == gender])

len_all_gender

{nan: 0,
 'Female': 2130,
 'Male': 1301,
 'I prefer not to say': 48,
 'Queer': 13,
 'Transgender': 3,
 'I prefer not to say,Male': 3,
 'Gender Non-Conforming': 11}

### Race

In [1098]:
data_april['USI_DIVERSITY_QUESTION_RACE'].unique()

array([nan, 'White', 'Black or African American', 'Asian',
       'Hispanic or Latinx', 'Asian,I prefer not to say', 'Multi-racial',
       'I prefer not to say', 'Asian,Multi-racial,White',
       'Black or African American,Hispanic or Latinx',
       'Black or African American,Multi-racial',
       'Asian,I prefer not to say,Multi-racial',
       'Hispanic or Latinx,White',
       'American Indian or Alaska Native,Black or African American',
       'Black or African American,Hispanic or Latinx,Multi-racial',
       'Hispanic or Latinx,Multi-racial',
       'American Indian or Alaska Native,Black or African American,Hispanic or Latinx,Multi-racial',
       'American Indian or Alaska Native,White',
       'Asian,Black or African American,Multi-racial',
       'Black or African American,Multi-racial,White',
       'Asian,Multi-racial', 'Black or African American,White',
       'Multi-racial,White', 'Asian,White',
       'Asian,Native Hawaiian or Pacific Islader',
       'Black or African American,I prefer not to say',
       'Asian,Black or African American',
       'American Indian or Alaska Native',
       'American Indian or Alaska Native,Black or African American,Hispanic or Latinx,White',
       'American Indian or Alaska Native,Black or African American,Multi-racial',
       'I prefer not to say,White',
       'Asian,Black or African American,Hispanic or Latinx',
       'Hispanic or Latinx,Multi-racial,White',
       'Native Hawaiian or Pacific Islader', 'Asian,Hispanic or Latinx',
       'American Indian or Alaska Native,Hispanic or Latinx',
       'Asian,Hispanic or Latinx,Multi-racial'], dtype=object)

In [1099]:
data_april['USI_DIVERSITY_QUESTION_RACE'].nunique()

36

In [1015]:
# April per category
data_april.groupby(['POSITION_CATEGORY']).mean()

,[Unknown],Time In Application State: Lead,Time In Application State: New,Time In Application State: In-Review,Time In Application State: Interview,Time In Application State: Offered,Application Creation Month,num_applications,HIRED,INTERVIEW/Interview 1,...,INTERVIEW/On Hold: Pre Interview,INTERVIEW/On Hold: Pre-interview,INTERVIEW/Ready for Mgr Review,IN_REVIEW/Application Review,IN_REVIEW/ON HOLD: PRE-SCREEN,IN_REVIEW/On Hold: Pre Screen,REJECTED,TRANSFERRED,WITHDRAWN,Time In Application Process
POSITION_CATEGORY,,,,,,,,,,,,,,,,,,,,,
Apprentice Teacher,0.00000,0.408537,3.768293,3.347561,3.268293,0.695122,4,1,0.048780,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.774390,0.073171,0.103659,4.176829
College Completion,0.00000,0.481172,2.322176,1.564854,2.347280,0.251046,4,1,0.025105,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.949791,0.004184,0.020921,2.803347
Core Teacher,0.00000,1.357019,2.568458,9.433276,4.409012,0.512998,4,1,0.046794,0.000000,...,0.001733,0.000000,0.001733,0.000000,0.005199,0.000000,0.662045,0.006932,0.275563,3.925477
General Teacher,0.00000,1.488827,3.393855,6.673184,2.377095,0.122905,4,1,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.801676,0.030726,0.167598,4.882682
Home Office,0.00206,1.104396,1.712912,2.691621,0.901786,0.024725,4,1,0.002747,0.001374,...,0.000000,0.000000,0.000000,0.000687,0.000000,0.000000,0.937500,0.000687,0.057005,2.817308
Instructional Leadership,0.00000,1.321678,2.377622,1.720280,0.769231,0.041958,4,1,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.965035,0.006993,0.027972,3.699301
Operational Leadership,0.00000,3.402077,0.991098,1.017804,0.491098,0.148368,4,1,0.010386,0.000000,...,0.000000,0.001484,0.000000,0.000000,0.000000,0.000000,0.973294,0.001484,0.013353,4.393175
Regional Support Staff,0.00000,0.000000,5.156863,1.372549,0.000000,0.000000,4,1,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,5.156863
School Based Operations,0.00000,1.322275,2.383886,4.462085,1.279621,0.075829,4,1,0.009479,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.007109,0.000000,0.883886,0.000000,0.097156,3.706161
Specials Teacher,0.00000,2.357143,3.571429,7.303571,1.357143,0.000000,4,1,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.928571,0.000000,0.071429,5.928571
Student Support,0.00000,1.640449,4.668539,6.278090,2.710674,0.067416,4,1,0.016854,0.000000,...,0.002809,0.000000,0.000000,0.000000,0.008427,0.002809,0.938202,0.002809,0.028090,6.308989
Summer Teaching Fellows,0.00000,1.000000,1.000000,0.000000,0.000000,0.000000,4,1,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,2.000000

In [1016]:
# April in for all applications
data_april.groupby(['num_applications']).mean()

,[Unknown],Time In Application State: Lead,Time In Application State: New,Time In Application State: In-Review,Time In Application State: Interview,Time In Application State: Offered,Application Creation Month,HIRED,INTERVIEW/Interview 1,INTERVIEW/ON Hold: Pre-Interview,INTERVIEW/On Hold: Pre Interview,INTERVIEW/On Hold: Pre-interview,INTERVIEW/Ready for Mgr Review,IN_REVIEW/Application Review,IN_REVIEW/ON HOLD: PRE-SCREEN,IN_REVIEW/On Hold: Pre Screen,REJECTED,TRANSFERRED,WITHDRAWN,Time In Application Process
num_applications,,,,,,,,,,,,,,,,,,,,
1,0.000644,1.68012,2.302705,3.90833,1.680335,0.152855,4,0.01331,0.000429,0.000215,0.000429,0.000215,0.000215,0.000215,0.001932,0.000215,0.891155,0.007514,0.084156,3.982825

In [1017]:
# Fill nan i desired columns
data[['Time In Application State: Lead', 'Time In Application State: New',
           'Time In Application State: In-Review', 'Time In Application State: Interview',
           'Time In Application State: Offered']] = data[['Time In Application State: Lead', 
            'Time In Application State: New',
           'Time In Application State: In-Review', 'Time In Application State: Interview',
           'Time In Application State: Offered']].fillna(value=0)

In [1018]:
# creat new column with sum
data['Time In Application Process'] = data['Time In Application State: Lead'] + data['Time In Application State: New']
+ data['Time In Application State: In-Review'] + data['Time In Application State: Interview']
+ data['Time In Application State: Offered'] 

data.head(3)

,CANDIDATE_ID_x,APPLICATION_ID,JOB_REF_ID,JOB_TITLE,DEPARTMENT,POSITION_CATEGORY,POSITION,REGION,USI_DIVERSITY_QUESTION_RACE,USI_DIVERSITY_QUESTION_GENDER,...,[Unknown],Time In Application State: Lead,Time In Application State: New,Time In Application State: In-Review,Time In Application State: Interview,Time In Application State: Offered,Source,Application Creation Month,num_applications,Time In Application Process
0,e9263572-f945-4e2e-bf66-6ae0c25c56f5,f72b1b7e-f35f-4f2a-aa79-cb29c8ff73e6,REF13L,Dean of Students,Student Services,Student Support,Dean Of Students,Troy,NaN,NaN,...,False,1.0,1.0,0.0,13.0,0.0,Katie Yezzi,4,1,2.0
1,ae78dd81-4525-4825-8981-a0f9bc301c14,ae78dd81-4525-4825-8981-a0f9bc301c14,REF8Q,Apprentice Teacher (Immediate Start SY 18-19),Teaching and Instruction,Apprentice Teacher,Apprentice Teacher,Rochester,Multi-racial,Female,...,False,2.0,6.0,9.0,12.0,1.0,Brandi Moore,1,1,8.0
2,97c1bcb8-eb94-4d19-b324-f9ce5c2ed7c0,2a787e27-f8a2-4eab-9cfd-5884a357fc15,REF93W,Receptionist (Immediate Start),School-Based Operations,School Based Operations,Receptionist,Newark,I prefer not to say,Female,...,False,0.0,1.0,21.0,0.0,0.0,Indeed,5,1,1.0

In [1019]:
# all time span per category
data.groupby(['POSITION_CATEGORY']).mean()

,[Unknown],Time In Application State: Lead,Time In Application State: New,Time In Application State: In-Review,Time In Application State: Interview,Time In Application State: Offered,Application Creation Month,num_applications,Time In Application Process
POSITION_CATEGORY,,,,,,,,,
Apprentice Teacher,0.000487,0.635036,3.084672,3.718248,1.211192,0.250608,5.209246,1.0,3.719708
College Completion,0.000000,0.870675,2.646623,2.084020,1.163921,0.084020,5.275124,1.0,3.517298
Core Teacher,0.000179,1.101236,2.760616,5.982978,2.935137,0.296004,5.069163,1.0,3.861853
General Teacher,0.000000,0.731915,3.245593,5.016413,1.423708,0.066869,5.155015,1.0,3.977508
Home Office,0.001472,0.323703,2.891700,3.747884,0.854435,0.075267,5.350478,1.0,3.215403
Instructional Leadership,0.001052,0.841220,2.778128,1.219769,0.446898,0.166141,4.719243,1.0,3.619348
Operational Leadership,0.003205,2.176282,1.753663,1.431777,0.555403,0.104853,3.814560,1.0,3.929945
Regional Support Staff,0.000000,0.670635,3.575397,2.027778,1.619048,0.095238,6.162698,1.0,4.246032
School Based Operations,0.000723,0.879942,4.295323,2.981678,0.753375,0.028689,4.643684,1.0,5.175265
Specials Teacher,0.003802,0.286439,4.749049,6.141952,2.841572,0.192649,4.937896,1.0,5.035488
Student Support,0.000403,0.662364,5.277128,4.887455,1.478015,0.040742,3.859217,1.0,5.939492
Summer Teaching Fellows,0.000000,8.438356,10.250000,25.626712,23.671233,4.260274,2.160959,1.0,18.688356

In [1020]:
# all timespan for all applications
data.groupby(['num_applications']).mean()

,[Unknown],Time In Application State: Lead,Time In Application State: New,Time In Application State: In-Review,Time In Application State: Interview,Time In Application State: Offered,Application Creation Month,Time In Application Process
num_applications,,,,,,,,
1,0.000977,1.903053,3.304522,3.982707,1.478813,0.154719,4.874241,5.207575

### Top sources for applicants

Column Source

In [892]:
data_april['Source'].head()

0             Katie Yezzi
4        RoxburyPrep Jobs
22    Default Career Page
33              IndeedPro
38              IndeedPro
Name: Source, dtype: object

In [893]:
data_april['Source'].isnull().sum()

0

In March no missing data. In total data only 5 rows with missing data.

This could be nice to see development over time...

In [894]:
data_april['Source'].nunique()

134

In [895]:
data['Source'].nunique()

481

The reason to very high number of unique answers is that the unique name of person recommended is one source.

In [896]:
d = data_april['Source'].unique()
all_sources = {}
len_all_sources = {}
for i in d:
    all_sources[i] = data_april[data_april['Source'] == i]
    len_all_sources[i] = len(data_april[data_april['Source'] == i])

len_all_sources

{'Katie Yezzi': 2,
 'RoxburyPrep Jobs': 35,
 'Default Career Page': 396,
 'IndeedPro': 1119,
 'DVEC Greater Philly Teacher Job Fair': 26,
 'CamdenPrep Jobs': 30,
 'LinkedIn': 476,
 'SmartRecruiters': 30,
 'LinkedIn Recruiter': 663,
 'RochesterPrep Jobs': 37,
 'Indeed': 630,
 'Tyana Velazquez': 5,
 'Website_GeneralCareers': 74,
 'Paije Robinson': 1,
 'Internal Career Page': 8,
 'LinkedIn Limited Listings': 86,
 'Laura-ann Jones': 1,
 'Glassdoor': 112,
 'Home Office and Operations': 8,
 'Briyyah McClain': 3,
 'Teach for America': 2,
 'Apprentice Teachers': 6,
 'NorthStar Jobs': 89,
 'Titciana Barros': 1,
 'Rosemay Paul': 1,
 'Todd Levine': 1,
 'ShiAsia Kelly': 2,
 'TroyPrep Jobs': 22,
 'Social Referral': 8,
 'Indeed Headhunting': 9,
 'The Muse': 12,
 'Rutgers U - Newark': 14,
 'Chantaya King': 4,
 'Handshake-Apprentice Teacher': 4,
 'Idealist': 47,
 'Leadership': 16,
 'Monster': 9,
 'Symplicity-ES Teacher': 3,
 'NJ School Jobs': 25,
 'Uncommon NYC': 13,
 'SmartJobs': 32,
 'Symplicity': 109,
 'Massachusetts Education Recruitment Consortium': 18,
 'Handshake': 99,
 'Job Widget': 17,
 'Rutgers NJ Statewide Career Fair': 31,
 'Home Office': 16,
 'School Spring': 25,
 'TeacherDeadlineCampaign': 6,
 'Marthalyn Johnson': 2,
 'Teaching Positions': 14,
 'NJ Teacher Job Fair': 31,
 'Summer Teaching Fellows': 3,
 'City Year Boston Career Fair': 2,
 'Symplicity-Apprentice Teacher': 5,
 'School Operations': 12,
 'Association of Independent Colleges and Universities in NJ Teacher Fair': 8,
 'Metro NY Charter School Career Fair': 13,
 'Sherla Thermitus': 6,
 'Tasha Grant': 1,
 'NYU': 2,
 'Carl Slater': 4,
 'Clark Atlanta University': 4,
 'Facebook Ad': 4,
 'Edsurge Spring Fair': 6,
 'Collin Cherubim': 2,
 'Student Support': 6,
 'ZipRecruiter Organic': 3,
 'Handshake-Summer Teaching Fellow': 8,
 'Brittany Rumph': 6,
 'Google Search': 9,
 'Handshake Middle School Teachers': 7,
 'Jooble': 2,
 'Kara James': 1,
 'Angelica Johnson': 2,
 'Jessica Lisboa': 1,
 'Jopwell': 3,
 'Taysiah Varnie': 1,
 'Google Display Ad - Deadline': 2,
 'Samantha Gladd': 1,
 'TeShia Robinson': 1,
 'HIreNYC': 11,
 'Facebook Ad - Deadline': 4,
 'Ben Greenstone': 1,
 'TFA Connect': 2,
 'Alexa Young': 2,
 'Nyree Addison': 1,
 'Candarine': 5,
 'Cyre Guadalupe': 1,
 'Gary Johnson': 1,
 'Shammel Turnbore': 1,
 'Christie Clarke': 2,
 'Internal Transfer': 2,
 'Sara Griffin': 1,
 'Howard University': 6,
 'The Black Perspective': 1,
 'Alexandra Harvey': 1,
 'Rider Career Fair': 3,
 'Adrienne Avery': 2,
 'Callista Regis': 2,
 'Kaitlyn Coirazza': 1,
 'Handshake High School Teachers': 5,
 'National Alliance for Public Charter Schools': 1,
 'Victoria LalamaCabrera': 1,
 'Mariah Major': 1,
 'Joemi Espinal': 2,
 'LinkedIn Post': 4,
 'Megan Clough': 1,
 'Makaela Simmons': 1,
 'Lauren Catlett': 3,
 'Uncommon': 1,
 'Donny Harris': 1,
 'Symplicity-NonTeaching': 2,
 'Raven Cruz': 1,
 'WayUp Organic': 3,
 'TCNJ Education Interview Days': 1,
 'Alexis Ulaj': 2,
 'Javonna Brown': 1,
 'Jamie Morrison': 2,
 'Boston Diversity Career Fair for Teachers': 1,
 'Future Leaders Incubator': 1,
 'Bridgespan': 1,
 'Boris Zarkhi': 1,
 'Noelle Van der Tuin': 1,
 'Americorps Alumni': 1,
 'Daphne Capellan': 3,
 'Rowan Career Fair': 1,
 'Indeed All Jobs': 1,
 'Leandra Cooke': 1,
 'Neuvoo': 1,
 'Johanna Glaude': 1,
 'Other': 4,
 'Sposato': 1,
 'Jeni McDermott': 1}

In [897]:
data_april.shape

(4658, 54)

In [898]:
data_april.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4658 entries, 0 to 33757
Data columns (total 54 columns):
CANDIDATE_ID_x                                    4504 non-null object
APPLICATION_ID                                    4658 non-null object
JOB_REF_ID                                        4504 non-null object
JOB_TITLE                                         4504 non-null object
DEPARTMENT                                        4504 non-null object
POSITION_CATEGORY                                 4504 non-null object
POSITION                                          4504 non-null object
REGION                                            3048 non-null object
USI_DIVERSITY_QUESTION_RACE                       3545 non-null object
USI_DIVERSITY_QUESTION_GENDER                     3509 non-null object
USI_UNCOMMON_AFFILIATION                          3663 non-null object
USI_GPA                                           1633 non-null object
USI_TEACHER_CERT                                  889 non-null object
USI_TEACHING_EXPERIENCE                           1108 non-null object
USI_HEARD_ABOUT_UNCOMMON                          3402 non-null object
USI_OTHER_AFFILIATION                             3260 non-null object
CANDIDATE_ID_y                                    4658 non-null object
Application Creation Date                         4658 non-null datetime64[ns]
Job Title                                         4658 non-null object
Position                                          4504 non-null object
Position Category                                 4504 non-null object
Region                                            3048 non-null object
Grade Level                                       1885 non-null object
HO Team                                           1456 non-null object
Application Status                                4658 non-null object
Application Transfer Date                         35 non-null object
Application Status Before Rejection               4151 non-null object
Application Rejection Date                        4151 non-null object
Rejection Reason                                  3478 non-null object
Application Status Before Withdrawal              392 non-null object
Application Withdrawal Date                       392 non-null object
Withdrawal Reason                                 391 non-null object
Application field: Secondary Withdrawal Reason    0 non-null object
[Unknown]                                         4658 non-null bool
Time In Application State: Lead                   1043 non-null float64
Time In Application State: New                    3774 non-null float64
Time In Application State: In-Review              3267 non-null float64
Time In Application State: Interview              313 non-null float64
Time In Application State: Offered                56 non-null float64
Source                                            4658 non-null object
Application Creation Month                        4658 non-null int64
num_applications                                  4658 non-null int64
HIRED                                             4658 non-null uint8
INTERVIEW/Interview 1                             4658 non-null uint8
INTERVIEW/ON Hold: Pre-Interview                  4658 non-null uint8
INTERVIEW/On Hold: Pre Interview                  4658 non-null uint8
INTERVIEW/On Hold: Pre-interview                  4658 non-null uint8
INTERVIEW/Ready for Mgr Review                    4658 non-null uint8
IN_REVIEW/Application Review                      4658 non-null uint8
IN_REVIEW/ON HOLD: PRE-SCREEN                     4658 non-null uint8
IN_REVIEW/On Hold: Pre Screen                     4658 non-null uint8
REJECTED                                          4658 non-null uint8
TRANSFERRED                                       4658 non-null uint8
WITHDRAWN                                         4658 non-null uint8
dtypes: bool(1), datetime64[ns](1), float64(5), int64(2), object(33), uint8(12)
memory usage: 1.6+ MB

In [899]:
# join sourcemap and data_march with inner join into new dataframe
data_april_source = pd.merge(left=data_april, right=sourcemap.drop_duplicates(subset=['Source']), left_on='Source', right_on='Source', how='left')

data_april_source.shape

(4658, 57)

In [900]:
data_april_source.head(3)

,CANDIDATE_ID_x,APPLICATION_ID,JOB_REF_ID,JOB_TITLE,DEPARTMENT,POSITION_CATEGORY,POSITION,REGION,USI_DIVERSITY_QUESTION_RACE,USI_DIVERSITY_QUESTION_GENDER,...,INTERVIEW/Ready for Mgr Review,IN_REVIEW/Application Review,IN_REVIEW/ON HOLD: PRE-SCREEN,IN_REVIEW/On Hold: Pre Screen,REJECTED,TRANSFERRED,WITHDRAWN,Adjusted_Source,Adjusted_Source_SubType,Adjusted_Source_Type
0,e9263572-f945-4e2e-bf66-6ae0c25c56f5,f72b1b7e-f35f-4f2a-aa79-cb29c8ff73e6,REF13L,Dean of Students,Student Services,Student Support,Dean Of Students,Troy,NaN,NaN,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,6233f272-d866-4927-b901-8bab73213a29,6233f272-d866-4927-b901-8bab73213a29,REF52A,Middle School ELA Teacher (Immediate Start),Teaching and Instruction,Core Teacher,MS ELA Teacher,Boston,White,Female,...,0,0,0,0,0,0,0,RoxburyPrep Jobs,Outreach Site,Headhunting
2,39f00a50-7902-4a7c-9c6c-ba6228e8c3d5,538d93b0-4f0d-4266-a0db-77c26c4d5f33,REF56L,Middle School History Teacher (Immediate Start),Teaching and Instruction,Core Teacher,MS History Teacher,Rochester,NaN,NaN,...,0,0,0,0,0,0,0,Default Career Page,Default Career Page,CareerPages

In [901]:
data_april_source.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4658 entries, 0 to 4657
Data columns (total 57 columns):
CANDIDATE_ID_x                                    4504 non-null object
APPLICATION_ID                                    4658 non-null object
JOB_REF_ID                                        4504 non-null object
JOB_TITLE                                         4504 non-null object
DEPARTMENT                                        4504 non-null object
POSITION_CATEGORY                                 4504 non-null object
POSITION                                          4504 non-null object
REGION                                            3048 non-null object
USI_DIVERSITY_QUESTION_RACE                       3545 non-null object
USI_DIVERSITY_QUESTION_GENDER                     3509 non-null object
USI_UNCOMMON_AFFILIATION                          3663 non-null object
USI_GPA                                           1633 non-null object
USI_TEACHER_CERT                                  889 non-null object
USI_TEACHING_EXPERIENCE                           1108 non-null object
USI_HEARD_ABOUT_UNCOMMON                          3402 non-null object
USI_OTHER_AFFILIATION                             3260 non-null object
CANDIDATE_ID_y                                    4658 non-null object
Application Creation Date                         4658 non-null datetime64[ns]
Job Title                                         4658 non-null object
Position                                          4504 non-null object
Position Category                                 4504 non-null object
Region                                            3048 non-null object
Grade Level                                       1885 non-null object
HO Team                                           1456 non-null object
Application Status                                4658 non-null object
Application Transfer Date                         35 non-null object
Application Status Before Rejection               4151 non-null object
Application Rejection Date                        4151 non-null object
Rejection Reason                                  3478 non-null object
Application Status Before Withdrawal              392 non-null object
Application Withdrawal Date                       392 non-null object
Withdrawal Reason                                 391 non-null object
Application field: Secondary Withdrawal Reason    0 non-null object
[Unknown]                                         4658 non-null bool
Time In Application State: Lead                   1043 non-null float64
Time In Application State: New                    3774 non-null float64
Time In Application State: In-Review              3267 non-null float64
Time In Application State: Interview              313 non-null float64
Time In Application State: Offered                56 non-null float64
Source                                            4658 non-null object
Application Creation Month                        4658 non-null int64
num_applications                                  4658 non-null int64
HIRED                                             4658 non-null uint8
INTERVIEW/Interview 1                             4658 non-null uint8
INTERVIEW/ON Hold: Pre-Interview                  4658 non-null uint8
INTERVIEW/On Hold: Pre Interview                  4658 non-null uint8
INTERVIEW/On Hold: Pre-interview                  4658 non-null uint8
INTERVIEW/Ready for Mgr Review                    4658 non-null uint8
IN_REVIEW/Application Review                      4658 non-null uint8
IN_REVIEW/ON HOLD: PRE-SCREEN                     4658 non-null uint8
IN_REVIEW/On Hold: Pre Screen                     4658 non-null uint8
REJECTED                                          4658 non-null uint8
TRANSFERRED                                       4658 non-null uint8
WITHDRAWN                                         4658 non-null uint8
Adjusted_Source                                   4569 non-null object
Adjusted_Source_SubType                           4569 non-null object
Adjusted_Source_Type                              4544 non-null object
dtypes: bool(1), datetime64[ns](1), float64(5), int64(2), object(36), uint8(12)
memory usage: 1.7+ MB

In [902]:
data_april_source['Adjusted_Source_Type'].unique()

array([nan, 'Headhunting', 'CareerPages', 'Job Board', 'Fairs/Events',
       'SmartRecruiters', 'Internal', 'Enhanced Job Board', 'Agency',
       'Referrals', 'Digital Strategy', 'Other'], dtype=object)

In [903]:
data_april_source['Adjusted_Source_Type'].nunique()

11

In [904]:
data_april_source['Adjusted_Source_SubType'].unique()

array([nan, 'Outreach Site', 'Default Career Page', 'Indeed',
       'Job Fair - Other', 'LinkedIn', 'SmartRecruiters',
       'website traffic', 'Internal', 'Glassdoor', 'Teacher Placement',
       'External Referral', 'The Muse', 'Job Fair - University',
       'Handshake', 'Idealist', 'Paid Job Boards', 'Symplicity',
       'NJ School Jobs', 'SmartJobs', 'Other', 'School Spring',
       'DeadlineCampaign', 'Event', 'Facebook', 'Free Job Board',
       'Google', 'Jopwell', 'University Job Board'], dtype=object)

In [905]:
data_april_source['Adjusted_Source_SubType'].nunique()

28

To begin with I'm going to use Adjusted_Source_Type

In [906]:
# See how many applications and application status per Adjusted_Source_Type
sum_adjsourcetype = data_april_source.groupby(['Adjusted_Source_Type']).sum()

sum_adjsourcetype

,[Unknown],Time In Application State: Lead,Time In Application State: New,Time In Application State: In-Review,Time In Application State: Interview,Time In Application State: Offered,Application Creation Month,num_applications,HIRED,INTERVIEW/Interview 1,INTERVIEW/ON Hold: Pre-Interview,INTERVIEW/On Hold: Pre Interview,INTERVIEW/On Hold: Pre-interview,INTERVIEW/Ready for Mgr Review,IN_REVIEW/Application Review,IN_REVIEW/ON HOLD: PRE-SCREEN,IN_REVIEW/On Hold: Pre Screen,REJECTED,TRANSFERRED,WITHDRAWN
Adjusted_Source_Type,,,,,,,,,,,,,,,,,,,,
Agency,0.0,4.0,8.0,20.0,5.0,0.0,16,4,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
CareerPages,0.0,25.0,1654.0,2361.0,1623.0,106.0,2172,543,11.0,1.0,1.0,0.0,0.0,0.0,1.0,3.0,0.0,470.0,8.0,48.0
Digital Strategy,0.0,0.0,195.0,188.0,56.0,0.0,264,66,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,63.0,0.0,3.0
Enhanced Job Board,0.0,12.0,546.0,998.0,249.0,12.0,1312,328,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,309.0,1.0,16.0
Fairs/Events,0.0,1676.0,251.0,1423.0,249.0,20.0,688,172,2.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,123.0,4.0,41.0
Headhunting,0.0,4567.0,968.0,2215.0,1172.0,145.0,3624,906,9.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,848.0,6.0,41.0
Internal,3.0,7.0,9.0,11.0,54.0,146.0,40,10,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,2.0
Job Board,0.0,161.0,6668.0,9861.0,3454.0,180.0,9824,2456,19.0,1.0,0.0,1.0,1.0,1.0,0.0,4.0,0.0,2210.0,10.0,209.0
Other,0.0,0.0,61.0,25.0,43.0,0.0,68,17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0,0.0,1.0
Referrals,0.0,44.0,13.0,41.0,115.0,0.0,48,12,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,1.0
SmartRecruiters,0.0,218.0,25.0,153.0,132.0,41.0,120,30,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0,3.0,9.0

#### Adjusted_Source_Type per different month

In [907]:
data.head(3)

,CANDIDATE_ID_x,APPLICATION_ID,JOB_REF_ID,JOB_TITLE,DEPARTMENT,POSITION_CATEGORY,POSITION,REGION,USI_DIVERSITY_QUESTION_RACE,USI_DIVERSITY_QUESTION_GENDER,...,Withdrawal Reason,Application field: Secondary Withdrawal Reason,[Unknown],Time In Application State: Lead,Time In Application State: New,Time In Application State: In-Review,Time In Application State: Interview,Time In Application State: Offered,Source,Application Creation Month
0,e9263572-f945-4e2e-bf66-6ae0c25c56f5,f72b1b7e-f35f-4f2a-aa79-cb29c8ff73e6,REF13L,Dean of Students,Student Services,Student Support,Dean Of Students,Troy,NaN,NaN,...,NaN,NaN,False,1.0,1.0,NaN,13.0,NaN,Katie Yezzi,4
1,ae78dd81-4525-4825-8981-a0f9bc301c14,ae78dd81-4525-4825-8981-a0f9bc301c14,REF8Q,Apprentice Teacher (Immediate Start SY 18-19),Teaching and Instruction,Apprentice Teacher,Apprentice Teacher,Rochester,Multi-racial,Female,...,NaN,NaN,False,2.0,6.0,9.0,12.0,1.0,Brandi Moore,1
2,97c1bcb8-eb94-4d19-b324-f9ce5c2ed7c0,2a787e27-f8a2-4eab-9cfd-5884a357fc15,REF93W,Receptionist (Immediate Start),School-Based Operations,School Based Operations,Receptionist,Newark,I prefer not to say,Female,...,NaN,NaN,False,NaN,1.0,21.0,NaN,NaN,Indeed,5

In [ ]:
# Use previously creat num_applications column

In [909]:
# Dummy variables for Application Status column (and add to dataframe)
data = pd.concat([data, pd.get_dummies(data['Application Status'])], axis=1)

data.head(3)

,CANDIDATE_ID_x,APPLICATION_ID,JOB_REF_ID,JOB_TITLE,DEPARTMENT,POSITION_CATEGORY,POSITION,REGION,USI_DIVERSITY_QUESTION_RACE,USI_DIVERSITY_QUESTION_GENDER,...,LEAD,NEW,OFFER/Offer Created,OFFER/Offer Pending,OFFER/Ready to Make Offer,OFFER/Ready to OFfer,OFFER/Ready to Offer,REJECTED,TRANSFERRED,WITHDRAWN
0,e9263572-f945-4e2e-bf66-6ae0c25c56f5,f72b1b7e-f35f-4f2a-aa79-cb29c8ff73e6,REF13L,Dean of Students,Student Services,Student Support,Dean Of Students,Troy,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
1,ae78dd81-4525-4825-8981-a0f9bc301c14,ae78dd81-4525-4825-8981-a0f9bc301c14,REF8Q,Apprentice Teacher (Immediate Start SY 18-19),Teaching and Instruction,Apprentice Teacher,Apprentice Teacher,Rochester,Multi-racial,Female,...,0,0,0,0,0,0,0,0,0,0
2,97c1bcb8-eb94-4d19-b324-f9ce5c2ed7c0,2a787e27-f8a2-4eab-9cfd-5884a357fc15,REF93W,Receptionist (Immediate Start),School-Based Operations,School Based Operations,Receptionist,Newark,I prefer not to say,Female,...,0,0,0,0,0,0,0,0,0,0

In [910]:
data.shape

(33771, 75)

In [911]:
# join sourcemap and data with inner join into new dataframe
data_source = pd.merge(left=data, right=sourcemap.drop_duplicates(subset=['Source']), left_on='Source', right_on='Source', how='left')

data_source.shape

(33771, 78)

In [912]:
data_source.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33771 entries, 0 to 33770
Data columns (total 78 columns):
CANDIDATE_ID_x                                    32458 non-null object
APPLICATION_ID                                    33771 non-null object
JOB_REF_ID                                        32458 non-null object
JOB_TITLE                                         32458 non-null object
DEPARTMENT                                        32458 non-null object
POSITION_CATEGORY                                 32458 non-null object
POSITION                                          32458 non-null object
REGION                                            21590 non-null object
USI_DIVERSITY_QUESTION_RACE                       28060 non-null object
USI_DIVERSITY_QUESTION_GENDER                     27830 non-null object
USI_UNCOMMON_AFFILIATION                          28790 non-null object
USI_GPA                                           12929 non-null object
USI_TEACHER_CERT                                  8029 non-null object
USI_TEACHING_EXPERIENCE                           9786 non-null object
USI_HEARD_ABOUT_UNCOMMON                          27085 non-null object
USI_OTHER_AFFILIATION                             23210 non-null object
CANDIDATE_ID_y                                    33771 non-null object
Application Creation Date                         33771 non-null datetime64[ns]
Job Title                                         33771 non-null object
Position                                          32486 non-null object
Position Category                                 32486 non-null object
Region                                            21602 non-null object
Grade Level                                       14618 non-null object
HO Team                                           10884 non-null object
Application Status                                33771 non-null object
Application Transfer Date                         276 non-null object
Application Status Before Rejection               29391 non-null object
Application Rejection Date                        29391 non-null object
Rejection Reason                                  26491 non-null object
Application Status Before Withdrawal              2642 non-null object
Application Withdrawal Date                       2642 non-null object
Withdrawal Reason                                 2616 non-null object
Application field: Secondary Withdrawal Reason    7 non-null object
[Unknown]                                         33771 non-null bool
Time In Application State: Lead                   4883 non-null float64
Time In Application State: New                    28820 non-null float64
Time In Application State: In-Review              22027 non-null float64
Time In Application State: Interview              2153 non-null float64
Time In Application State: Offered                374 non-null float64
Source                                            33766 non-null object
Application Creation Month                        33771 non-null int64
num_applications                                  33771 non-null int64
HIRED                                             33771 non-null uint8
INTERVIEW/Interview 1                             33771 non-null uint8
INTERVIEW/Interview 2                             33771 non-null uint8
INTERVIEW/ON Hold: Pre-Interview                  33771 non-null uint8
INTERVIEW/On Hold: Post Interview                 33771 non-null uint8
INTERVIEW/On Hold: Post-Interview                 33771 non-null uint8
INTERVIEW/On Hold: Post-interview                 33771 non-null uint8
INTERVIEW/On Hold: Pre Interview                  33771 non-null uint8
INTERVIEW/On Hold: Pre-Interview                  33771 non-null uint8
INTERVIEW/On Hold: Pre-interview                  33771 non-null uint8
INTERVIEW/READY FOR HM REVIEW                     33771 non-null uint8
INTERVIEW/Ready for Mgr Review                    33771 non-null uint8
INTERVIEW/Reference Check                         33771 non-null uint8
IN_REVIEW/Application Review                      33771 non-null uint8
IN_REVIEW/Email Screen                            33771 non-null uint8
IN_REVIEW/Gathering More Info                     33771 non-null uint8
IN_REVIEW/ON HOLD: PRE-SCREEN                     33771 non-null uint8
IN_REVIEW/On Hold: Pre Screen                     33771 non-null uint8
IN_REVIEW/On Hold: Pre-screen                     33771 non-null uint8
IN_REVIEW/Phone Screen                            33771 non-null uint8
IN_REVIEW/Skills Task                             33771 non-null uint8
IN_REVIEW/Video Screen                            33771 non-null uint8
IN_REVIEW/Waiting for Transcript                  33771 non-null uint8
LEAD                                              33771 non-null uint8
NEW                                               33771 non-null uint8
OFFER/Offer Created                               33771 non-null uint8
OFFER/Offer Pending                               33771 non-null uint8
OFFER/Ready to Make Offer                         33771 non-null uint8
OFFER/Ready to OFfer                              33771 non-null uint8
OFFER/Ready to Offer                              33771 non-null uint8
REJECTED                                          33771 non-null uint8
TRANSFERRED                                       33771 non-null uint8
WITHDRAWN                                         33771 non-null uint8
Adjusted_Source                                   33185 non-null object
Adjusted_Source_SubType                           33185 non-null object
Adjusted_Source_Type                              32977 non-null object
dtypes: bool(1), datetime64[ns](1), float64(5), int64(2), object(36), uint8(33)
memory usage: 12.7+ MB

In [913]:
data_source['Application Creation Date'].max()

Timestamp('2019-09-02 00:00:00')

In [914]:
data_source['Application Creation Date'].min()

Timestamp('2019-01-11 00:00:00')

January and September are not full month. Therefor only look at following month for 2019:
February
March 
April
May
June
July
August

In [915]:
data_source['Application Creation Month'].unique()

array([4, 1, 5, 2, 6, 3, 7, 8, 9])

In [916]:
#Different month
february = data_source[data_source['Application Creation Month'] == 2]
march = data_source[data_source['Application Creation Month'] == 3]
april = data_source[data_source['Application Creation Month'] == 4]
may = data_source[data_source['Application Creation Month'] == 5]
june = data_source[data_source['Application Creation Month'] == 6]
july = data_source[data_source['Application Creation Month'] == 7]
august = data_source[data_source['Application Creation Month'] == 8]

In [917]:
# See how many applications and application status per Adjusted_Source_Type per month
feb_sourcetype = february.groupby(['Adjusted_Source_Type']).sum()
mar_sourcetype = march.groupby(['Adjusted_Source_Type']).sum()
apr_sourcetype = april.groupby(['Adjusted_Source_Type']).sum()
may_sourcetype = may.groupby(['Adjusted_Source_Type']).sum()
jun_sourcetype = june.groupby(['Adjusted_Source_Type']).sum()
jul_sourcetype = july.groupby(['Adjusted_Source_Type']).sum()
aug_sourcetype = august.groupby(['Adjusted_Source_Type']).sum()

#### Save to CSV

In [918]:
feb_sourcetype.to_csv('february_adj_source_type.csv')

In [919]:
mar_sourcetype.to_csv('march_adj_source_type.csv')

In [920]:
apr_sourcetype.to_csv('april_adj_source_type.csv')

In [921]:
may_sourcetype.to_csv('may_adj_source_type.csv')

In [922]:
jun_sourcetype.to_csv('june_adj_source_type.csv')

In [923]:
jul_sourcetype.to_csv('july_adj_source_type.csv')

In [924]:
aug_sourcetype.to_csv('august_adj_source_type.csv')

### Number of applications other months

In [1054]:
february.shape

(2998, 78)

In [1055]:
march.shape

(4367, 78)

In [1056]:
april.shape

(4658, 78)

In [1057]:
may.shape

(6249, 78)

In [1058]:
june.shape

(5751, 78)

In [1059]:
july.shape

(4922, 78)

In [1060]:
august.shape

(2984, 78)

In [1062]:
# on average nr of applications
(2998+4367+4658+6249+5751+4922+2984)/7

4561.285714285715

### Number of job postings other months

In [1063]:
february['JOB_TITLE'].nunique()

94

In [1064]:
march['JOB_TITLE'].nunique()

93

In [1065]:
april['JOB_TITLE'].nunique()

98

In [1066]:
may['JOB_TITLE'].nunique()

100

In [1067]:
june['JOB_TITLE'].nunique()

97

In [1068]:
july['JOB_TITLE'].nunique()

82

In [1069]:
august['JOB_TITLE'].nunique()

71

### Job Title and Position Category

In [1090]:
april['POSITION_CATEGORY'].unique()

array(['Student Support', 'Core Teacher', 'School Based Operations',
       'Operational Leadership', 'College Completion',
       'Apprentice Teacher', 'Home Office', 'General Teacher',
       'Instructional Leadership', 'Regional Support Staff',
       'Specials Teacher', 'Summer Teaching Fellows', nan], dtype=object)

In [1094]:
 april[april['POSITION_CATEGORY'] == 'Regional Support Staff']['JOB_TITLE'].nunique()

1

In [1092]:
 april[april['POSITION_CATEGORY'] == 'General Teacher']['JOB_TITLE'].nunique()

3

In [1091]:
 april[april['POSITION_CATEGORY'] == 'College Completion']['JOB_TITLE'].nunique()

2

In [1078]:
# Number of unique job titles applied for in the position category Core Teacher in April
april[april['POSITION_CATEGORY'] == 'Core Teacher']['JOB_TITLE'].nunique()

30

In [1079]:
april[april['POSITION_CATEGORY'] == 'Operational Leadership']['JOB_TITLE'].nunique()

5

In [1080]:
april[april['POSITION_CATEGORY'] == 'Home Office']['JOB_TITLE'].nunique()

22

In [1081]:
april[april['POSITION_CATEGORY'] == 'Summer Teaching Fellows']['JOB_TITLE'].nunique()

1

In [1082]:
april[april['POSITION_CATEGORY'] == 'Apprentice Teacher']['JOB_TITLE'].nunique()

4

In [1083]:
april[april['POSITION_CATEGORY'] == 'Student Support']['JOB_TITLE'].nunique()

13

In [1084]:
april[april['POSITION_CATEGORY'] == 'Specials Teacher']['JOB_TITLE'].nunique()

7

In [1085]:
april[april['POSITION_CATEGORY'] == 'School Based Operations']['JOB_TITLE'].nunique()

5

In [1089]:
april[april['POSITION_CATEGORY'] == 'Instructional Leadership']['JOB_TITLE'].nunique()

5

In [1095]:
1+3+2+30+5+22+1+4+13+7+5+5

98